import { StyleSheet } from 'react-native';

export const palette = {
    red: `#d83b42`,
    blue: `#0874f9`,
    ink: `#14213d`,
    green: `#21a668`,
    pink: `#cd4c8c`,
    white: `#ffffff`,
    muted: `#6b7280`,
    border: `#e3e7ee`,
    yellow: `#b7860b`,
    purple: `#8054d7`,
    orange: `#d97722`,
    background: `#f7f8fa`,
};

export const accents = {
    ink: { color: palette.ink, background: `#eef0f5` },
    red: { color: palette.red, background: `#fff0ee` },
    blue: { color: palette.blue, background: `#edf4ff` },
    pink: { color: palette.pink, background: `#fdeef5` },
    green: { color: palette.green, background: `#edf8f1` },
    yellow: { color: palette.yellow, background: `#fff8db` },
    purple: { color: palette.purple, background: `#f3edff` },
    orange: { color: palette.orange, background: `#fff1e6` },
};

export function createLandingStyles(fontsLoaded: boolean) {
    const regular = fontsLoaded ? `Inter_400Regular` : undefined;
    const medium = fontsLoaded ? `Inter_500Medium` : undefined;
    const semibold = fontsLoaded ? `Inter_600SemiBold` : undefined;
    const bold = fontsLoaded ? `Inter_700Bold` : undefined;
    const heavy = fontsLoaded ? `Inter_800ExtraBold` : undefined;

    return StyleSheet.create({
        screen: {
            flex: 1,
            backgroundColor: palette.background,
        },
        scroll: {
            flex: 1,
        },
        content: {
            width: `100%`,
            maxWidth: 1344,
            paddingBottom: 32,
            alignSelf: `center`,
        },
        stickyHeader: {
            zIndex: 10,
            paddingBottom: 16,
            backgroundColor: `rgba(247, 248, 250, 0.4)`,
        },
        header: {
            gap: 20,
            flexWrap: `wrap`,
            paddingTop: 20,
            paddingBottom: 28,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        headerControls: {
            gap: 14,
            maxWidth: `100%`,
            flexWrap: `wrap`,
            marginLeft: `auto`,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `flex-end`,
        },
        brand: {
            gap: 10,
            flexDirection: `row`,
            alignItems: `center`,
        },
        brandName: {
            fontSize: 18,
            lineHeight: 19,
            fontFamily: heavy,
            color: palette.ink,
            letterSpacing: -0.6,
        },
        menu: {
            gap: 4,
            maxWidth: `100%`,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        menuButton: {
            gap: 7,
            minHeight: 44,
            paddingVertical: 10,
            paddingHorizontal: 8,
            flexDirection: `row`,
            alignItems: `center`,
        },
        menuLabel: {
            fontSize: 13,
            fontFamily: semibold,
            color: palette.ink,
        },
        pressed: {
            opacity: 0.65,
        },
        hero: {
            gap: 30,
            paddingTop: 20,
            paddingBottom: 38,
        },
        heroWide: {
            gap: 48,
            paddingTop: 46,
            paddingBottom: 60,
            flexDirection: `row`,
            alignItems: `center`,
        },
        heroCopy: {
            flex: 1,
        },
        eyebrowLine: {
            gap: 8,
            marginBottom: 20,
            flexDirection: `row`,
            alignItems: `center`,
        },
        eyebrowRadar: {
            width: 7,
            height: 7,
            position: `relative`,
        },
        eyebrowRadarRing: {
            top: 0,
            left: 0,
            width: 7,
            height: 7,
            borderWidth: 1,
            borderRadius: 4,
            position: `absolute`,
        },
        eyebrowDot: {
            width: 7,
            height: 7,
            borderRadius: 4,
        },
        eyebrow: {
            fontSize: 11,
            lineHeight: 18,
            letterSpacing: 1.6,
            fontFamily: semibold,
            color: palette.blue,
            textTransform: `uppercase`,
        },
        heading: {
            fontSize: 49,
            lineHeight: 54,
            letterSpacing: -2.8,
            fontFamily: heavy,
            color: palette.ink,
        },
        headingWide: {
            fontSize: 68,
            lineHeight: 74,
            letterSpacing: -4,
        },
        heroDescription: {
            fontSize: 15,
            maxWidth: 470,
            lineHeight: 25,
            marginTop: 20,
            fontFamily: regular,
            color: palette.muted,
        },
        heroArtwork: {
            padding: 20,
            borderWidth: 1,
            borderRadius: 22,
            backgroundColor: `#eef2f8`,
            borderColor: palette.border,
        },
        heroArtworkWide: {
            width: 360,
            padding: 26,
        },
        artworkHeading: {
            gap: 18,
            marginBottom: 24,
            flexDirection: `row`,
            alignItems: `center`,
        },
        artworkTitle: {
            fontSize: 23,
            lineHeight: 27,
            fontFamily: heavy,
            color: palette.ink,
            letterSpacing: -0.7,
        },
        artworkSubtitle: {
            fontSize: 10,
            marginTop: 8,
            letterSpacing: 1.2,
            fontFamily: medium,
            color: palette.muted,
        },
        artworkRows: {
            gap: 10,
        },
        artworkRow: {
            gap: 12,
            minHeight: 52,
            borderRadius: 11,
            paddingHorizontal: 14,
            flexDirection: `row`,
            alignItems: `center`,
        },
        artworkRowLabel: {
            flex: 1,
            fontSize: 13,
            fontFamily: semibold,
        },
        searchSection: {
            marginBottom: 36,
        },
        searchTabs: {
            gap: 4,
            flexDirection: `row`,
            alignItems: `flex-end`,
        },
        searchTabContainer: {
            flex: 1,
            overflow: `hidden`,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
        },
        searchTab: {
            gap: 6,
            minHeight: 43,
            paddingVertical: 10,
            paddingHorizontal: 8,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `center`,
        },
        searchTabActive: {
            backgroundColor: `rgba(255, 255, 255, 0.15)`,
        },
        searchTabLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: palette.white,
        },
        searchBox: {
            gap: 10,
            padding: 8,
            paddingLeft: 17,
            borderWidth: 1,
            borderRadius: 14,
            borderTopLeftRadius: 0,
            borderTopRightRadius: 0,
            flexDirection: `row`,
            alignItems: `center`,
        },
        searchIcon: {
            width: 20,
            height: 20,
            position: `relative`,
        },
        searchIconLayer: {
            top: 0,
            left: 0,
            position: `absolute`,
        },
        searchInput: {
            flex: 1,
            fontSize: 14,
            minHeight: 44,
            paddingVertical: 0,
            fontFamily: regular,
            color: palette.ink,
        },
        searchButtonContainer: {
            borderRadius: 9,
            overflow: `hidden`,
        },
        searchButton: {
            gap: 8,
            minHeight: 46,
            borderRadius: 9,
            paddingHorizontal: 15,
            flexDirection: `row`,
            alignItems: `center`,
        },
        searchButtonLabel: {
            fontSize: 13,
            fontFamily: semibold,
            color: palette.white,
        },
        searchHint: {
            fontSize: 11,
            lineHeight: 18,
            marginTop: 10,
            fontFamily: regular,
            color: palette.muted,
        },
        sectionHeader: {
            gap: 10,
            marginBottom: 18,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        sectionTitle: {
            fontSize: 21,
            lineHeight: 29,
            fontFamily: bold,
            color: palette.ink,
            letterSpacing: -0.7,
        },
        sectionCaption: {
            fontSize: 11,
            fontFamily: regular,
            color: palette.muted,
        },
        categorySection: {
            marginBottom: 44,
        },
        categories: {
            gap: 12,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        category: {
            padding: 16,
            minHeight: 167,
            borderWidth: 1,
            borderRadius: 14,
            borderColor: palette.border,
            backgroundColor: palette.white,
        },
        categorySelected: {
            borderColor: palette.blue,
            backgroundColor: `#f0f6ff`,
        },
        categoryIcon: {
            width: 39,
            height: 35,
            borderRadius: 9,
            marginBottom: 15,
            alignItems: `center`,
            justifyContent: `center`,
        },
        categoryLabel: {
            fontSize: 14,
            lineHeight: 20,
            fontFamily: bold,
            color: palette.ink,
        },
        categoryDescription: {
            fontSize: 11,
            lineHeight: 17,
            marginTop: 4,
            fontFamily: regular,
            color: palette.muted,
        },
        categoryCount: {
            fontSize: 10,
            marginTop: 12,
            fontFamily: medium,
            color: palette.muted,
        },
        explore: {
            marginBottom: 48,
        },
        exploreControls: {
            gap: 12,
            marginBottom: 20,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        topicTabs: {
            gap: 4,
            flexDirection: `row`,
        },
        topicTab: {
            gap: 5,
            minHeight: 40,
            borderRadius: 8,
            paddingHorizontal: 11,
            flexDirection: `row`,
            alignItems: `center`,
        },
        topicTabActive: {
            backgroundColor: palette.ink,
        },
        topicTabLabel: {
            fontSize: 12,
            fontFamily: semibold,
            color: palette.muted,
        },
        topicTabLabelActive: {
            color: palette.white,
        },
        viewControls: {
            gap: 2,
            padding: 3,
            borderWidth: 1,
            borderRadius: 9,
            flexDirection: `row`,
            borderColor: palette.border,
        },
        viewButton: {
            width: 34,
            height: 34,
            borderRadius: 6,
            alignItems: `center`,
            justifyContent: `center`,
        },
        viewButtonActive: {
            backgroundColor: palette.white,
        },
        directoryGrid: {
            gap: 18,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        directoryCard: {
            overflow: `hidden`,
            borderWidth: 1,
            borderRadius: 15,
            borderColor: palette.border,
            backgroundColor: palette.white,
        },
        directoryPreview: {
            padding: 21,
            paddingBottom: 12,
        },
        directoryCardHeader: {
            gap: 12,
            marginBottom: 20,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        directoryMonogram: {
            width: 44,
            height: 44,
            borderRadius: 11,
            alignItems: `center`,
            justifyContent: `center`,
        },
        directoryInitials: {
            fontSize: 15,
            fontFamily: bold,
        },
        featuredBadge: {
            gap: 4,
            paddingVertical: 5,
            paddingHorizontal: 7,
            borderRadius: 6,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: `#f4f6f9`,
        },
        featuredBadgeLabel: {
            fontSize: 9,
            fontFamily: medium,
            color: palette.muted,
        },
        directoryTitleRow: {
            gap: 10,
            marginBottom: 8,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        directoryTitle: {
            flex: 1,
            fontSize: 18,
            lineHeight: 24,
            fontFamily: bold,
            color: palette.ink,
            letterSpacing: -0.5,
        },
        directoryDescription: {
            fontSize: 12,
            minHeight: 54,
            lineHeight: 19,
            fontFamily: regular,
            color: palette.muted,
        },
        directoryFooter: {
            gap: 8,
            paddingLeft: 21,
            paddingRight: 11,
            paddingBottom: 11,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        directoryLabel: {
            fontSize: 10,
            borderRadius: 5,
            paddingVertical: 5,
            fontFamily: medium,
            paddingHorizontal: 7,
            color: palette.muted,
            backgroundColor: `#f4f6f9`,
        },
        bookmarkButton: {
            width: 40,
            height: 40,
            borderRadius: 9,
            alignItems: `center`,
            justifyContent: `center`,
        },
        bookmarkButtonSaved: {
            backgroundColor: `#edf4ff`,
        },
        emptyState: {
            gap: 16,
            padding: 34,
            borderWidth: 1,
            borderRadius: 15,
            alignItems: `center`,
            borderColor: palette.border,
            backgroundColor: palette.white,
        },
        emptyTitle: {
            fontSize: 19,
            fontFamily: bold,
            color: palette.ink,
            textAlign: `center`,
        },
        emptyDescription: {
            fontSize: 13,
            maxWidth: 320,
            lineHeight: 22,
            textAlign: `center`,
            fontFamily: regular,
            color: palette.muted,
        },
        clearButton: {
            gap: 7,
            minHeight: 44,
            borderRadius: 8,
            paddingHorizontal: 14,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: `#edf4ff`,
        },
        clearButtonLabel: {
            fontSize: 12,
            fontFamily: semibold,
            color: palette.blue,
        },
        footer: {
            gap: 24,
            borderTopWidth: 1,
            paddingTop: 32,
            borderColor: palette.border,
        },
        footerStatement: {
            fontSize: 25,
            lineHeight: 33,
            fontFamily: bold,
            color: palette.ink,
            letterSpacing: -0.8,
        },
        footerBottom: {
            gap: 18,
            flexWrap: `wrap`,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        footerBrand: {
            gap: 8,
            flexDirection: `row`,
            alignItems: `center`,
        },
        footerBrandLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: palette.ink,
        },
        copyright: {
            fontSize: 10,
            fontFamily: regular,
            color: palette.muted,
        },
        footerDetails: {
            gap: 12,
            flexWrap: `wrap`,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        footerLink: {
            gap: 7,
            minHeight: 44,
            flexDirection: `row`,
            alignItems: `center`,
        },
        footerLinkLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: palette.blue,
        },
        modalBackdrop: {
            flex: 1,
            padding: 24,
            alignItems: `center`,
            justifyContent: `center`,
            backgroundColor: `rgba(20, 33, 61, 0.38)`,
        },
        modalCard: {
            padding: 26,
            width: `100%`,
            maxWidth: 480,
            borderRadius: 20,
            backgroundColor: palette.white,
        },
        modalHeader: {
            gap: 12,
            marginBottom: 24,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        modalTitle: {
            fontSize: 27,
            lineHeight: 34,
            marginBottom: 12,
            fontFamily: bold,
            color: palette.ink,
            letterSpacing: -0.8,
        },
        modalDescription: {
            fontSize: 14,
            lineHeight: 23,
            marginBottom: 24,
            fontFamily: regular,
            color: palette.muted,
        },
        sampleNotice: {
            fontSize: 11,
            lineHeight: 18,
            paddingTop: 18,
            borderTopWidth: 1,
            marginTop: 22,
            fontFamily: regular,
            color: palette.muted,
            borderColor: palette.border,
        },
        modalVisitButton: {
            gap: 8,
            minHeight: 48,
            marginTop: 22,
            marginBottom: 12,
            borderWidth: 1,
            borderRadius: 9,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `center`,
            borderColor: palette.blue,
        },
        modalVisitLabel: {
            fontSize: 12,
            fontFamily: semibold,
            color: palette.blue,
        },
        modalSaveButton: {
            gap: 8,
            minHeight: 48,
            borderRadius: 9,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `center`,
            backgroundColor: palette.blue,
        },
    });
}
