import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: { overflow: `hidden`, paddingVertical: 72 },
  compact: { paddingVertical: 36 },
  banner: { paddingVertical: 28 },
  contained: { borderRadius: 20 },
  content: { zIndex: 1, width: `100%`, alignSelf: `center` },
  card: { gap: 28, padding: 30, borderWidth: 1, borderRadius: 20, alignItems: `center` },
  cardCompact: { gap: 20, padding: 24 },
  cardBanner: { padding: 0, borderWidth: 0, borderRadius: 0, backgroundColor: `transparent` },
  copy: { gap: 14 },
  blogCopy: { gap: 12 },
  heading: { fontSize: 29, lineHeight: 38, letterSpacing: -0.8 },
  headingCompact: { fontSize: 24, lineHeight: 32, letterSpacing: -0.6 },
  blogHeading: { fontSize: 28, lineHeight: 36, letterSpacing: -0.9 },
  bannerHeading: { gap: 10, flexDirection: `row`, alignItems: `center` },
  bannerHeadingLabel: { flexShrink: 1, fontSize: 24, lineHeight: 32 },
  actions: { gap: 14, maxWidth: `100%`, flexWrap: `wrap`, alignItems: `flex-start` },
  primary: { gap: 9, minHeight: 48, maxWidth: `100%`, borderRadius: 8, paddingVertical: 14, paddingHorizontal: 18, flexDirection: `row`, alignItems: `center` },
  primaryLabel: { flexShrink: 1 },
  secondary: { gap: 8, minHeight: 44, maxWidth: `100%`, flexDirection: `row`, alignItems: `center` },
  secondaryLabel: { flexShrink: 1 },
  pattern: { opacity: 0.14, position: `absolute` },
  dotsTop: { top: 18, left: 12 },
  dotsBottom: { right: 12, bottom: 18 },
  ringsTop: { top: -90, left: -90 },
  ringsBottom: { right: -80, bottom: -80 },
  gridTop: { top: -30, left: -40 },
  gridBottom: { right: -40, bottom: -30 },
});
