import { StyleSheet } from 'react-native';

export const createHeroAtomStyles = (foreground: string) => StyleSheet.create({
    atom: {
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 0,
        opacity: 0.48,
        position: `absolute`,
        alignItems: `center`,
        justifyContent: `center`,
    },
    stage: {
        width: 300,
        height: 300,
        position: `relative`,
    },
    orbit: {
        ...StyleSheet.absoluteFillObject,
    },
    track: {
        top: 94,
        left: 10,
        width: 280,
        height: 112,
        opacity: 0.42,
        borderWidth: 1,
        borderRadius: 140,
        position: `absolute`,
    },
    electron: {
        top: 143,
        left: 143,
        width: 14,
        height: 14,
        borderRadius: 7,
        position: `absolute`,
        alignItems: `center`,
        justifyContent: `center`,
    },
    electronGlow: {
        top: -6,
        left: -6,
        right: -6,
        bottom: -6,
        opacity: 0.12,
        borderRadius: 13,
        position: `absolute`,
    },
    electronCore: {
        width: 7,
        height: 7,
        borderRadius: 4,
    },
    halo: {
        top: 103,
        left: 103,
        width: 94,
        height: 94,
        opacity: 0.07,
        borderWidth: 1,
        borderRadius: 47,
        position: `absolute`,
        borderColor: foreground,
    },
    nucleus: {
        top: 132,
        left: 132,
        width: 36,
        height: 36,
        opacity: 0.7,
        borderWidth: 1,
        borderRadius: 18,
        position: `absolute`,
        alignItems: `center`,
        justifyContent: `center`,
        borderColor: foreground,
    },
    nucleusCore: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: foreground,
    },
});
