import type { BlogArticle } from '../blog/articles';
import { getPageNavigation } from '../navigation/siteNavigation';
import type { SiteNavigationId } from '../navigation/siteNavigation';
import type { PageCtaContent } from '../../components/PageCta/PageCta.types';

type PageCtaPage = `api` | `docs` | `terms` | `privacy` | `pricing` | `contact` | `discover` | `profile` | `sign-in` | `sign-up` | `blog-directory`;

const createNavigationCta = (
  page: SiteNavigationId,
  content: Pick<PageCtaContent, `title` | `pattern` | `description` | `primary`>,
): PageCtaContent => {
  const { icon, tone, label } = getPageNavigation(page);
  return { ...content, icon, tone, eyebrow: label, id: `${page}-intro-cta` };
};

export const navigationCtas: Record<Exclude<SiteNavigationId, `blog` | `pricing` | `contact` | `discover`>, PageCtaContent> = {
  about: createNavigationCta(`about`, {
    pattern: `rings`,
    title: `See what we're bringing together`,
    description: `Explore collections for tools, learning, communities, and more.`,
    primary: { icon: `sparkles`, href: `/discover`, label: `Discover Directories` },
  }),
  api: createNavigationCta(`api`, {
    pattern: `grid`,
    title: `Explore the ideas behind the API`,
    description: `Read the browsing guide while the public API is in development.`,
    primary: { icon: `learning`, href: `/docs`, label: `Read the Guide` },
  }),
  docs: createNavigationCta(`docs`, {
    pattern: `grid`,
    title: `Put the browsing guide to work`,
    description: `Try a category, search for a topic, and explore the sample collection.`,
    primary: { icon: `sparkles`, href: `/discover`, label: `Try the Preview` },
  }),
  terms: createNavigationCta(`terms`, {
    pattern: `dots`,
    title: `Get the full picture`,
    description: `Pair these terms with a closer look at how your information is handled.`,
    primary: { icon: `shield`, href: `/privacy`, label: `Read the Privacy Policy` },
  }),
  privacy: createNavigationCta(`privacy`, {
    pattern: `rings`,
    title: `Browse with more context`,
    description: `Learn how the current preview works before your next discovery.`,
    primary: { icon: `learning`, href: `/docs`, label: `Read the Browsing Guide` },
  }),
};

export const pageCtas: Record<PageCtaPage, PageCtaContent> = {
  api: {
    tone: `blue`,
    icon: `tools`,
    pattern: `grid`,
    id: `api-page-cta`,
    eyebrow: `For Curious Builders`,
    title: `Explore the experience behind the API plans`,
    description: `There isn't a public API yet. Browse the preview or read the guide to see how directories, search, and filters work today.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { href: `/docs`, icon: `file-text`, label: `Read the Docs` },
  },
  docs: {
    tone: `green`,
    pattern: `dots`,
    icon: `learning`,
    id: `docs-page-cta`,
    eyebrow: `Try It Yourself`,
    title: `Turn this guide into your next discovery`,
    description: `Choose a category, try a search, and open a listing in the sample catalogue. Keep a few bookmarks during your visit.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { href: `/blog`, icon: `file-text`, label: `Read the Blog` },
  },
  terms: {
    tone: `purple`,
    icon: `shield`,
    pattern: `rings`,
    id: `terms-page-cta`,
    eyebrow: `Keep Exploring`,
    title: `A clearer path to your next find`,
    description: `Browse the sample collection with these terms in mind, or read how Directory Directory handles your information.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { icon: `shield`, href: `/privacy`, label: `Read the Privacy Policy` },
  },
  privacy: {
    tone: `green`,
    icon: `shield`,
    pattern: `rings`,
    id: `privacy-page-cta`,
    eyebrow: `Browse at Your Pace`,
    title: `Explore with a little more context`,
    description: `Public browsing doesn't require an account. See the sample directories or read the guide to understand the current experience.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { href: `/docs`, icon: `file-text`, label: `Read the Docs` },
  },
  pricing: {
    tone: `green`,
    pattern: `grid`,
    icon: `business`,
    id: `pricing-page-cta`,
    eyebrow: `Your Starting Point`,
    title: `Start with the free preview`,
    description: `Browse and bookmark sample listings today. Paid subscriptions and their additional features are coming soon.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore the Free Preview` },
    secondary: { href: `/docs`, icon: `file-text`, label: `Read the Docs` },
  },
  contact: {
    tone: `red`,
    icon: `mail`,
    pattern: `dots`,
    id: `contact-page-cta`,
    eyebrow: `Keep the Ideas Flowing`,
    title: `Let a good question lead somewhere`,
    description: `Your message preview stays on this page. While you shape your idea, explore the sample directories or learn more about the project.`,
    secondary: { icon: `info`, href: `/about`, label: `About the Project` },
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
  },
  discover: {
    tone: `green`,
    pattern: `grid`,
    icon: `sparkles`,
    id: `discover-page-cta`,
    eyebrow: `A Little More Direction`,
    title: `Find the story behind your next discovery`,
    description: `Learn how directories work, what makes a collection useful, and how to explore niche resources in the blog.`,
    primary: { href: `/blog`, icon: `file-text`, label: `Explore the Blog` },
    secondary: { href: `/docs`, icon: `learning`, label: `Read the Browsing Guide` },
  },
  profile: {
    tone: `blue`,
    icon: `user`,
    pattern: `dots`,
    id: `profile-page-cta`,
    eyebrow: `Follow Your Curiosity`,
    title: `Your next discovery is still out there`,
    description: `Explore the public collection or find a guide for your next project. Browsing is available with or without a local demo profile.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { href: `/blog`, icon: `file-text`, label: `Read the Blog` },
  },
  'sign-in': {
    tone: `blue`,
    pattern: `grid`,
    icon: `log-in`,
    id: `sign-in-page-cta`,
    eyebrow: `The Door Is Open`,
    title: `Curiosity doesn't need a sign-in`,
    description: `Browse sample directories and read the blog while you decide whether to use a local demo profile.`,
    primary: { icon: `grid`, href: `/discover`, label: `Browse Directories` },
    secondary: { href: `/blog`, icon: `file-text`, label: `Explore the Blog` },
  },
  'sign-up': {
    tone: `purple`,
    pattern: `dots`,
    icon: `user-plus`,
    id: `sign-up-page-cta`,
    eyebrow: `Your Own Starting Point`,
    title: `Start exploring at your own pace`,
    description: `The collection and blog are open to browse. Take a look around before or after creating a local demo profile.`,
    primary: { icon: `grid`, href: `/discover`, label: `Browse Directories` },
    secondary: { href: `/blog`, icon: `file-text`, label: `Explore the Blog` },
  },
  'blog-directory': {
    tone: `purple`,
    pattern: `dots`,
    icon: `sparkles`,
    id: `blog-directory-cta`,
    eyebrow: `Your Next Discovery`,
    title: `Ready to put your curiosity to work?`,
    description: `Explore our directory of directories.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
  },
};

const articleCtas: Record<string, Omit<PageCtaContent, `id`>> = {
  'what-is-a-directory': {
    tone: `blue`,
    pattern: `dots`,
    icon: `learning`,
    eyebrow: `From the Story to the Screen`,
    title: `See the directory idea in action`,
    description: `From printed guides to online collections, organization gives discovery a starting point. Explore the sample directory experience or learn when to browse and search.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { icon: `search`, label: `Compare Browsing and Search`, href: `/blog/directory-vs-search-engine` },
  },
  'directory-vs-search-engine': {
    tone: `green`,
    icon: `search`,
    pattern: `rings`,
    eyebrow: `Try Both Starting Points`,
    title: `Put browsing and search to work together`,
    description: `Choose a category, narrow your question, and explore the sample collection. For your next topic, follow a specialist trail with our niche discovery guide.`,
    primary: { icon: `grid`, href: `/discover`, label: `Browse the Collection` },
    secondary: { icon: `sparkles`, label: `Find Niche Resources`, href: `/blog/discover-niche-resources` },
  },
  'choose-a-trustworthy-directory': {
    tone: `purple`,
    icon: `shield`,
    pattern: `grid`,
    eyebrow: `Bring Your Questions Along`,
    title: `Make your next discovery an informed one`,
    description: `Use the preview to practice comparing directory descriptions. Then learn how browsing and focused searches can help you investigate the options you find.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore the Preview` },
    secondary: { icon: `search`, label: `Read the Search Guide`, href: `/blog/directory-vs-search-engine` },
  },
  'discover-niche-resources': {
    tone: `red`,
    pattern: `dots`,
    icon: `sparkles`,
    eyebrow: `Give Curiosity a Direction`,
    title: `Start a trail worth following`,
    description: `Pick a category in the sample collection and see where it leads. When you gather useful links of your own, give them the organization they need to stay helpful.`,
    primary: { icon: `grid`, href: `/discover`, label: `Choose a Starting Point` },
    secondary: { icon: `bookmark`, label: `Organize Your Finds`, href: `/blog/organize-a-resource-collection` },
  },
  'organize-a-resource-collection': {
    tone: `blue`,
    icon: `bookmark`,
    pattern: `grid`,
    eyebrow: `Give Your Links a Purpose`,
    title: `Explore how a collection comes together`,
    description: `Browse the sample categories and listing previews for an example of organized discovery. Learn how a directory of directories adds another useful layer.`,
    primary: { icon: `grid`, href: `/discover`, label: `Browse the Preview` },
    secondary: { icon: `list`, label: `Explore the Bigger Picture`, href: `/blog/why-a-directory-of-directories` },
  },
  'why-a-directory-of-directories': {
    tone: `purple`,
    icon: `list`,
    pattern: `rings`,
    eyebrow: `Find the Collection First`,
    title: `Choose a collection to begin your next search`,
    description: `Explore the sample directory listings by category, or take a closer look at how specialist collections can help you discover unfamiliar resources.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore Directories` },
    secondary: { icon: `sparkles`, label: `Read the Niche Discovery Guide`, href: `/blog/discover-niche-resources` },
  },
  'directories-for-local-discovery': {
    tone: `green`,
    icon: `places`,
    pattern: `dots`,
    eyebrow: `Keep Exploring Close to Home`,
    title: `Bring a little more direction to local discovery`,
    description: `Browse the sample collection to explore the directory format. Before planning a real visit, use our guide to assess a collection and confirm details directly.`,
    primary: { icon: `grid`, href: `/discover`, label: `Explore the Collection` },
    secondary: { icon: `shield`, label: `Assess a Directory`, href: `/blog/choose-a-trustworthy-directory` },
  },
};

export const getArticleCta = (article: BlogArticle): PageCtaContent => ({
  ...(articleCtas[article.id] ?? articleCtas[`what-is-a-directory`]),
  id: `article-cta-${article.slug}`,
});
