import { StyleSheet } from 'react-native';
import { getNativePalette } from '../../shared/theme/nativePalette';

export function createDirectoryExplorerStyles(fontsLoaded: boolean, isDark: boolean) {
    const colors = getNativePalette(isDark);
    const medium = fontsLoaded ? `Inter_500Medium` : undefined;
    const semibold = fontsLoaded ? `Inter_600SemiBold` : undefined;
    const bold = fontsLoaded ? `Inter_700Bold` : undefined;
    const regular = fontsLoaded ? `Inter_400Regular` : undefined;

    return StyleSheet.create({
        exploreCaption: {
            fontSize: 11,
            borderRadius: 7,
            paddingVertical: 5,
            paddingHorizontal: 10,
            fontFamily: medium,
            color: colors.blue,
            backgroundColor: colors.blueSoft,
        },
        exploreTitleGroup: {
            gap: 10,
            flex: 1,
            minWidth: 0,
            flexDirection: `row`,
            alignItems: `center`,
        },
        exploreTitleAccent: {
            width: 32,
            height: 32,
            flexShrink: 0,
            borderRadius: 9,
            alignItems: `center`,
            justifyContent: `center`,
        },
        exploreTitle: {
            flexShrink: 1,
        },
        explore: {
            paddingTop: 28,
            borderTopWidth: 1,
            marginBottom: 48,
            borderColor: colors.border,
        },
        exploreStickyControls: {
            zIndex: 4,
            elevation: 4,
            borderBottomWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.background,
        },
        exploreControls: {
            gap: 8,
            padding: 4,
            borderWidth: 1,
            borderRadius: 12,
            marginBottom: 16,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: colors.border,
            backgroundColor: colors.surface,
            justifyContent: `space-between`,
        },
        topicTabsScroll: {
            flex: 1,
            minWidth: 0,
        },
        topicTabs: {
            gap: 4,
            flexDirection: `row`,
            alignItems: `center`,
        },
        topicTab: {
            gap: 4,
            flexShrink: 0,
            minHeight: 30,
            borderRadius: 8,
            paddingHorizontal: 8,
            flexDirection: `row`,
            alignItems: `center`,
        },
        topicTabActive: {
            backgroundColor: getNativePalette(false).ink,
        },
        topicTabLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: colors.muted,
        },
        topicTabLabelActive: {
            color: colors.white,
        },
        viewControls: {
            gap: 2,
            padding: 2,
            flexShrink: 0,
            borderWidth: 1,
            borderRadius: 9,
            flexDirection: `row`,
            borderColor: colors.border,
        },
        viewButton: {
            width: 28,
            height: 28,
            borderRadius: 6,
            alignItems: `center`,
            justifyContent: `center`,
        },
        viewButtonActive: {
            backgroundColor: colors.surface,
        },
        filterScroll: {
            flexGrow: 0,
            marginBottom: 12,
        },
        filterContent: {
            gap: 7,
            paddingVertical: 3,
            flexDirection: `row`,
            alignItems: `center`,
        },
        filterPill: {
            gap: 6,
            minHeight: 36,
            borderWidth: 1,
            borderRadius: 18,
            paddingHorizontal: 12,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: colors.border,
            backgroundColor: colors.surface,
        },
        filterPillActive: {
            borderColor: colors.blue,
            backgroundColor: colors.blueSoft,
        },
        filterLabel: {
            fontSize: 11,
            fontFamily: medium,
            color: colors.muted,
        },
        filterLabelActive: {
            color: colors.blue,
        },
        topicFilterHeading: {
            gap: 10,
            marginBottom: 5,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        topicFilterLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: colors.muted,
        },
        filterClear: {
            gap: 4,
            padding: 5,
            flexDirection: `row`,
            alignItems: `center`,
        },
        directoryGrid: {
            gap: 18,
            paddingTop: 10,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        directoryCard: {
            elevation: 2,
            borderWidth: 1,
            borderRadius: 15,
            shadowRadius: 12,
            shadowOpacity: 0.05,
            borderTopWidth: 3,
            overflow: `visible`,
            borderColor: colors.border,
            shadowColor: isDark ? `#000000` : `#14213d`,
            backgroundColor: colors.surface,
            shadowOffset: { width: 0, height: 5 },
        },
        directoryFolderTab: {
            top: -12,
            left: 21,
            width: 48,
            height: 12,
            position: `absolute`,
            borderTopLeftRadius: 6,
            borderTopRightRadius: 6,
        },
        directoryPreview: {
            padding: 21,
            paddingBottom: 12,
        },
        directoryCardHeader: {
            gap: 12,
            marginBottom: 20,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        directoryMonogram: {
            width: 44,
            height: 44,
            borderRadius: 11,
            alignItems: `center`,
            justifyContent: `center`,
        },
        directoryInitials: {
            fontSize: 15,
            fontFamily: bold,
        },
        featuredBadge: {
            gap: 4,
            paddingVertical: 5,
            paddingHorizontal: 7,
            borderRadius: 6,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: isDark ? `#243249` : `#f4f6f9`,
        },
        featuredBadgeLabel: {
            fontSize: 9,
            fontFamily: medium,
            color: colors.muted,
        },
        directoryTitleRow: {
            gap: 10,
            marginBottom: 8,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        directoryTitle: {
            flex: 1,
            fontSize: 18,
            lineHeight: 24,
            fontFamily: bold,
            color: colors.ink,
            letterSpacing: -0.5,
        },
        directoryDescription: {
            fontSize: 12,
            minHeight: 54,
            lineHeight: 19,
            fontFamily: regular,
            color: colors.muted,
        },
        directoryMetadata: {
            gap: 10,
            paddingHorizontal: 21,
            paddingBottom: 15,
        },
        directoryStatuses: {
            gap: 6,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        directoryStatus: {
            gap: 5,
            borderRadius: 6,
            paddingVertical: 4,
            paddingHorizontal: 6,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: isDark ? `#243249` : `#f4f6f9`,
        },
        statusDot: {
            width: 5,
            height: 5,
            borderRadius: 3,
        },
        directoryStatusLabel: {
            fontSize: 9,
            fontFamily: medium,
        },
        directoryTopics: {
            gap: 5,
            flexWrap: `wrap`,
            flexDirection: `row`,
        },
        directoryTopic: {
            borderRadius: 6,
            paddingVertical: 5,
            paddingHorizontal: 7,
            backgroundColor: colors.blueSoft,
        },
        directoryTopicLabel: {
            fontSize: 10,
            fontFamily: medium,
            color: colors.blue,
        },
        directoryWebsite: {
            gap: 5,
            minHeight: 32,
            flexDirection: `row`,
            alignItems: `center`,
            alignSelf: `flex-start`,
        },
        directoryWebsiteLabel: {
            fontSize: 11,
            fontFamily: semibold,
            color: colors.blue,
            textDecorationLine: `underline`,
        },
        directoryFeedback: {
            paddingBottom: 14,
            paddingHorizontal: 21,
        },
        directoryFooter: {
            gap: 8,
            paddingTop: 8,
            paddingLeft: 21,
            paddingRight: 11,
            paddingBottom: 11,
            borderTopWidth: 1,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: colors.border,
            borderBottomLeftRadius: 14,
            borderBottomRightRadius: 14,
            backgroundColor: isDark ? `#17263b` : `#fbfcfe`,
            justifyContent: `space-between`,
        },
        directoryLabel: {
            fontSize: 10,
            borderRadius: 5,
            paddingVertical: 5,
            fontFamily: medium,
            paddingHorizontal: 7,
            color: colors.muted,
            backgroundColor: isDark ? `#243249` : `#f4f6f9`,
        },
        bookmarkButton: {
            width: 40,
            height: 40,
            borderRadius: 9,
            alignItems: `center`,
            justifyContent: `center`,
        },
        bookmarkButtonSaved: {
            backgroundColor: colors.blueSoft,
        },
        emptyState: {
            gap: 16,
            padding: 34,
            borderWidth: 1,
            borderRadius: 15,
            alignItems: `center`,
            borderColor: colors.border,
            backgroundColor: colors.surface,
        },
        emptyTitle: {
            fontSize: 19,
            fontFamily: bold,
            color: colors.ink,
            textAlign: `center`,
        },
        emptyDescription: {
            fontSize: 13,
            maxWidth: 320,
            lineHeight: 22,
            textAlign: `center`,
            fontFamily: regular,
            color: colors.muted,
        },
        clearButton: {
            gap: 7,
            minHeight: 44,
            borderRadius: 8,
            paddingHorizontal: 14,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: colors.blueSoft,
        },
        clearButtonLabel: {
            fontSize: 12,
            fontFamily: semibold,
            color: colors.blue,
        },
    });
}
