import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: { overflow: `hidden`, marginBottom: 20, paddingVertical: 18, backgroundColor: `#0874f9` },
  content: { gap: 24, zIndex: 1, width: `100%`, maxWidth: 1280, alignSelf: `center`, flexDirection: `row`, alignItems: `flex-start`, paddingRight: 170 },
  contentSmall: { gap: 12, paddingRight: 110, flexDirection: `column` },
  copy: { gap: 8, flex: 1, maxWidth: 740 },
  copySmall: { flex: 0, width: `100%` },
  eyebrowRow: { gap: 7, flexDirection: `row`, alignItems: `center` },
  eyebrow: { color: `#ffffff`, opacity: 0.84, fontSize: 9, flexShrink: 1, letterSpacing: 1.2 },
  heading: { color: `#ffffff`, fontSize: 25, lineHeight: 32, letterSpacing: -0.7 },
  headingSmall: { fontSize: 22, lineHeight: 29 },
  description: { color: `#ffffff`, maxWidth: 740, fontSize: 15, lineHeight: 23, opacity: 0.92 },
  actions: { gap: 8, alignSelf: `center` },
  actionsSmall: { top: `50%`, right: 0, position: `absolute`, transform: [{ translateY: -36 }] },
  button: { gap: 6, minHeight: 32, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, flexDirection: `row`, alignItems: `center`, backgroundColor: `#ffffff` },
  buttonLabel: { color: `#18243a`, fontSize: 11, lineHeight: 14 },
  exploreButton: { backgroundColor: `#000000` },
  exploreLabel: { color: `#ffffff` },
  pressed: { opacity: 0.65 },
  decoration: { ...StyleSheet.absoluteFillObject },
  pattern: { opacity: 0.14, position: `absolute` },
  dots: { top: 14, left: 12 },
  rings: { right: -65, bottom: -145 },
  artwork: { top: 0, right: 0, width: 170, height: `100%`, overflow: `hidden`, position: `absolute`, alignItems: `center`, justifyContent: `center` },
  artworkSmall: { width: 50 },
  helix: { width: 180, transform: [{ rotate: `24deg` }] },
  helixNode: { left: 86, width: 8, height: 8, borderWidth: 1, borderRadius: 4, overflow: `hidden`, position: `absolute`, borderColor: `#000000`, backgroundColor: `#050505` },
  helixNodeShading: { top: 0, left: 0, width: 3, height: 3, opacity: 0.65, borderRadius: 1.5, position: `absolute`, backgroundColor: `#171717` },
  helixSegment: { left: 89.5, width: 1, height: 2, borderRadius: 1, position: `absolute`, backgroundColor: `#ffffff` },
  helixRung: { left: 55, width: 70, height: 1.5, opacity: 0.38, position: `absolute`, backgroundColor: `#ffffff` },
});
