import { StyleSheet } from 'react-native';
import { getNativePalette } from '../../shared/theme/nativePalette';

export const createPricingStyles = (isDark: boolean, fontsLoaded = false) => {
    const palette = getNativePalette(isDark);
    const bold = fontsLoaded ? `Inter_700Bold` : undefined;
    const medium = fontsLoaded ? `Inter_500Medium` : undefined;
    const regular = fontsLoaded ? `Inter_400Regular` : undefined;
    const semibold = fontsLoaded ? `Inter_600SemiBold` : undefined;

    return StyleSheet.create({
        section: {
            marginBottom: 40,
            paddingVertical: 72,
            backgroundColor: palette.blue,
        },
        content: {
            width: `100%`,
            maxWidth: 1200,
            alignSelf: `center`,
        },
        header: {
            maxWidth: 640,
            marginBottom: 40,
            alignSelf: `center`,
        },
        eyebrow: {
            fontSize: 10,
            lineHeight: 18,
            letterSpacing: 2,
            marginBottom: 14,
            fontFamily: semibold,
            textAlign: `center`,
            color: `rgba(255, 255, 255, 0.78)`,
            fontWeight: fontsLoaded ? undefined : `600`,
        },
        title: {
            fontSize: 38,
            lineHeight: 46,
            fontFamily: bold,
            color: palette.white,
            textAlign: `center`,
            letterSpacing: -1.2,
            fontWeight: fontsLoaded ? undefined : `700`,
        },
        description: {
            fontSize: 15,
            marginTop: 14,
            lineHeight: 24,
            fontFamily: regular,
            textAlign: `center`,
            color: `rgba(255, 255, 255, 0.84)`,
        },
        table: {
            elevation: 8,
            width: `100%`,
            shadowRadius: 28,
            flexWrap: `wrap`,
            borderRadius: 18,
            overflow: `hidden`,
            shadowOpacity: 0.18,
            flexDirection: `row`,
            shadowColor: isDark ? `#000000` : `#003878`,
            backgroundColor: palette.surface,
            shadowOffset: { width: 0, height: 14 },
        },
        plan: {
            padding: 24,
            paddingTop: 30,
            borderRightWidth: 1,
            borderBottomWidth: 1,
            position: `relative`,
            borderColor: palette.border,
        },
        lastColumn: {
            borderRightWidth: 0,
        },
        lastRow: {
            borderBottomWidth: 0,
        },
        highlightedPlan: {
            borderWidth: 2,
            borderColor: palette.blue,
            backgroundColor: palette.blueSoft,
        },
        folderTab: {
            top: 0,
            left: 24,
            width: 48,
            height: 7,
            position: `absolute`,
            borderBottomLeftRadius: 4,
            borderBottomRightRadius: 4,
        },
        markRow: {
            gap: 8,
            minHeight: 40,
            marginTop: 12,
            marginBottom: 10,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `space-between`,
        },
        badge: {
            fontSize: 9,
            flexShrink: 1,
            lineHeight: 14,
            borderRadius: 6,
            color: palette.blue,
            paddingVertical: 5,
            paddingHorizontal: 7,
            fontFamily: semibold,
            fontWeight: fontsLoaded ? undefined : `600`,
            backgroundColor: isDark ? `#1b3555` : `#e3efff`,
        },
        audience: {
            fontSize: 9,
            lineHeight: 16,
            minHeight: 16,
            letterSpacing: 1,
            color: palette.muted,
            fontFamily: semibold,
            textTransform: `uppercase`,
            fontWeight: fontsLoaded ? undefined : `600`,
        },
        planName: {
            marginTop: 5,
            fontSize: 23,
            lineHeight: 31,
            fontFamily: bold,
            fontWeight: fontsLoaded ? undefined : `700`,
        },
        summary: {
            fontSize: 12,
            marginTop: 10,
            minHeight: 63,
            lineHeight: 21,
            fontFamily: regular,
            color: palette.muted,
        },
        priceRow: {
            gap: 7,
            minHeight: 44,
            marginTop: 18,
            flexDirection: `row`,
            alignItems: `baseline`,
        },
        price: {
            fontSize: 34,
            lineHeight: 44,
            fontFamily: bold,
            color: palette.ink,
            letterSpacing: -1,
            fontWeight: fontsLoaded ? undefined : `700`,
        },
        priceCurrency: {
            fontSize: 24,
        },
        pricePeriod: {
            fontSize: 11,
            lineHeight: 18,
            fontFamily: medium,
            color: palette.muted,
            fontWeight: fontsLoaded ? undefined : `500`,
        },
        detail: {
            fontSize: 11,
            marginTop: 7,
            minHeight: 36,
            lineHeight: 18,
            fontFamily: regular,
            color: palette.muted,
        },
        features: {
            gap: 14,
            paddingTop: 22,
            marginTop: 24,
            marginBottom: 28,
            borderTopWidth: 1,
            borderTopColor: palette.border,
        },
        feature: {
            gap: 9,
            flexDirection: `row`,
            alignItems: `flex-start`,
        },
        featureLabel: {
            flex: 1,
            fontSize: 12,
            lineHeight: 19,
            fontFamily: regular,
            color: palette.ink,
        },
        action: {
            gap: 9,
            minHeight: 44,
            marginTop: `auto`,
            borderWidth: 1,
            borderRadius: 8,
            paddingVertical: 11,
            paddingHorizontal: 12,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: palette.border,
            justifyContent: `center`,
            backgroundColor: isDark ? `#1e2c43` : `#f7f9fc`,
        },
        actionLabel: {
            fontSize: 11,
            lineHeight: 18,
            color: palette.ink,
            fontFamily: semibold,
            fontWeight: fontsLoaded ? undefined : `600`,
        },
        pressed: {
            opacity: 0.65,
        },
        note: {
            gap: 8,
            maxWidth: 600,
            marginTop: 24,
            alignSelf: `center`,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `center`,
        },
        noteLabel: {
            fontSize: 11,
            flexShrink: 1,
            lineHeight: 18,
            fontFamily: regular,
            textAlign: `center`,
            color: `rgba(255, 255, 255, 0.82)`,
        },
    });
};
