import { StyleSheet } from 'react-native';
import { getNativePalette } from '../../shared/theme/nativePalette';

export function createAuthStyles(fontsLoaded: boolean, isDark: boolean) {
    const palette = getNativePalette(isDark);
    const regular = fontsLoaded ? `Inter_400Regular` : undefined;
    const semibold = fontsLoaded ? `Inter_600SemiBold` : undefined;
    const heavy = fontsLoaded ? `Inter_800ExtraBold` : undefined;

    return StyleSheet.create({
        screen: { flex: 1, backgroundColor: palette.background },
        body: { gap: 24 },
        content: { gap: 24, width: `100%`, maxWidth: 1440, paddingBottom: 32, alignSelf: `center` },
        stickyHeader: { gap: 16, zIndex: 10, paddingBottom: 16, backgroundColor: palette.headerScrim },
        header: { gap: 18, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
        headerControls: {
            gap: 10,
            maxWidth: `100%`,
            flexWrap: `wrap`,
            marginLeft: `auto`,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `flex-end`,
        },
        brand: { gap: 10, flexDirection: `row`, alignItems: `center` },
        brandName: { fontSize: 18, lineHeight: 19, fontFamily: heavy, color: palette.ink, letterSpacing: -0.6 },
        navigation: { gap: 8, maxWidth: `100%`, flexWrap: `wrap`, flexDirection: `row` },
        navigationLink: {
            gap: 6,
            minHeight: 44,
            borderRadius: 9,
            paddingVertical: 10,
            paddingHorizontal: 10,
            flexDirection: `row`,
            alignItems: `center`,
            backgroundColor: palette.surface,
        },
        navigationLabel: { fontSize: 12, fontFamily: semibold, color: palette.ink },
        layout: { gap: 28, width: `100%`, paddingVertical: 24 },
        layoutWide: { gap: 40, paddingVertical: 48, flexDirection: `row`, alignItems: `stretch` },
        story: { gap: 20, padding: 24, backgroundColor: palette.blueSoft },
        storyWide: { width: `50%`, padding: 40, justifyContent: `center` },
        storyHeading: { fontSize: 32, lineHeight: 38, letterSpacing: -1.2, fontFamily: heavy, color: palette.ink },
        storyHeadingWide: { fontSize: 44, lineHeight: 52 },
        storyAccent: { color: palette.blue },
        storyPreview: { gap: 8, flexWrap: `wrap`, flexDirection: `row` },
        storyChip: { gap: 6, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.surface },
        storyChipLabel: { fontSize: 10, fontFamily: semibold, color: palette.ink },
        panel: { width: `100%`, paddingVertical: 16, alignItems: `center` },
        panelWide: { flex: 1, width: undefined, paddingVertical: 32, paddingHorizontal: 24, justifyContent: `center` },
        panelContent: { gap: 24, width: `100%`, maxWidth: 520 },
        modes: { gap: 18, flexDirection: `row`, borderBottomWidth: 1, borderColor: palette.border },
        modeLink: { gap: 7, minHeight: 44, paddingBottom: 10, borderBottomWidth: 2, borderColor: `transparent`, flexDirection: `row`, alignItems: `center` },
        modeActive: { borderColor: palette.blue },
        modeLabel: { fontSize: 12, fontFamily: semibold, color: palette.muted },
        modeLabelActive: { color: palette.blue },
        eyebrow: { gap: 8, flexDirection: `row`, alignItems: `center` },
        eyebrowLabel: { fontSize: 10, letterSpacing: 1.4, fontFamily: semibold, color: palette.blue, textTransform: `uppercase` },
        progress: { gap: 10, flexDirection: `row` },
        step: { gap: 8, flex: 1 },
        stepTrack: { height: 3, borderRadius: 3, backgroundColor: palette.border },
        stepTrackActive: { backgroundColor: palette.blue },
        stepDetails: { gap: 5, flexDirection: `row`, alignItems: `center` },
        stepNumber: { width: 20, height: 20, borderRadius: 10, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.background },
        stepNumberActive: { backgroundColor: palette.blueSoft },
        stepNumberLabel: { fontSize: 10, fontFamily: semibold, color: palette.muted },
        stepLabel: { flex: 1, fontSize: 10, fontFamily: semibold, color: palette.muted },
        stepLabelActive: { color: palette.blue },
        form: { gap: 20 },
        headingGroup: { gap: 10 },
        heading: { fontSize: 36, lineHeight: 44, letterSpacing: -1.4, fontFamily: heavy, color: palette.ink },
        headingWide: { fontSize: 40, lineHeight: 48 },
        paragraph: { fontSize: 14, lineHeight: 24, fontFamily: regular, color: palette.muted },
        field: { gap: 8 },
        label: { fontSize: 12, fontFamily: semibold, color: palette.ink },
        inputFrame: {
            gap: 10,
            minHeight: 50,
            borderWidth: 1,
            borderRadius: 9,
            paddingHorizontal: 14,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: palette.border,
            backgroundColor: palette.background,
        },
        inputFrameError: { borderColor: palette.red },
        input: { flex: 1, minWidth: 0, fontSize: 15, minHeight: 48, lineHeight: 24, paddingVertical: 12, fontFamily: regular, color: palette.ink },
        passwordToggle: { gap: 5, minHeight: 44, flexDirection: `row`, alignItems: `center`, alignSelf: `flex-end` },
        passwordToggleLabel: { fontSize: 11, fontFamily: semibold, color: palette.blue },
        actions: { gap: 10, flexDirection: `row` },
        button: {
            gap: 8,
            flex: 1,
            minHeight: 48,
            borderRadius: 9,
            paddingHorizontal: 18,
            flexDirection: `row`,
            alignItems: `center`,
            justifyContent: `center`,
            backgroundColor: palette.blue,
        },
        buttonLabel: { fontSize: 13, fontFamily: semibold, color: palette.white },
        backButton: {
            gap: 7,
            minHeight: 48,
            borderWidth: 1,
            borderRadius: 9,
            paddingHorizontal: 14,
            flexDirection: `row`,
            alignItems: `center`,
            borderColor: palette.border,
            backgroundColor: palette.background,
        },
        backLabel: { fontSize: 12, fontFamily: semibold, color: palette.ink },
        backIcon: { transform: [{ rotate: `180deg` }] },
        progressLabel: { fontSize: 11, lineHeight: 18, textAlign: `center`, fontFamily: regular, color: palette.muted },
        error: { fontSize: 12, lineHeight: 22, fontFamily: regular, color: palette.red },
        notice: { gap: 8, paddingTop: 16, borderTopWidth: 1, flexDirection: `row`, alignItems: `flex-start`, borderColor: palette.border },
        noticeText: { flex: 1, fontSize: 11, lineHeight: 20, fontFamily: regular, color: palette.muted },
        skeleton: { borderRadius: 8, backgroundColor: palette.border },
        skeletonHeading: { width: `75%`, height: 36 },
        skeletonCopy: { width: `90%`, height: 16 },
        skeletonField: { height: 50 },
        switch: { gap: 10, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `center` },
        link: { gap: 7, minHeight: 44, flexDirection: `row`, alignItems: `center`, alignSelf: `flex-start` },
        linkLabel: { fontSize: 12, fontFamily: semibold, color: palette.blue },
        footer: { gap: 16, paddingTop: 20, borderTopWidth: 1, borderColor: palette.border },
        footerText: { fontSize: 11, lineHeight: 19, fontFamily: regular, color: palette.muted },
        footerLegal: { width: `100%`, marginVertical: -7.5, alignItems: `center` },
        footerNavigation: { justifyContent: `center` },
        footerNavigationLink: { minHeight: 0, paddingVertical: 0, paddingHorizontal: 0 },
        footerNavigationLabel: { fontSize: 11, lineHeight: 15 },
        footerCopyright: { textAlign: `center` },
        disabled: { opacity: 0.6 },
        pressed: { opacity: 0.65 },
    });
}
