export type CategoryId =
    | `tools`
    | `design`
    | `places`
    | `learning`
    | `business`
    | `lifestyle`
    | `technology`
    | `communities`;
export type DirectoryAccent = `ink` | `red` | `blue` | `pink` | `green` | `yellow` | `purple` | `orange`;

export interface DirectoryCategory {
    id: CategoryId;
    label: string;
    description: string;
}

export interface DirectoryEntry {
    id: string;
    href?: string;
    name: string;
    label: string;
    summary: string;
    initials: string;
    featured: boolean;
    category: CategoryId;
    accent: DirectoryAccent;
}

export const categories: DirectoryCategory[] = [
    {
        id: `design`,
        label: `Design`,
        description: `Ideas, references, and a little inspiration.`,
    },
    {
        id: `tools`,
        label: `Tools`,
        description: `Useful things for making your next thing.`,
    },
    {
        id: `communities`,
        label: `Communities`,
        description: `Good people doing interesting things.`,
    },
    {
        id: `places`,
        label: `Places`,
        description: `Find somewhere worth getting lost in.`,
    },
    {
        id: `learning`,
        label: `Learning`,
        description: `Fresh knowledge for your next bright idea.`,
    },
    {
        id: `technology`,
        label: `Technology`,
        description: `Explore what is new and what comes next.`,
    },
    {
        id: `business`,
        label: `Business`,
        description: `Resources for building something of your own.`,
    },
    {
        id: `lifestyle`,
        label: `Lifestyle`,
        description: `Good finds for a more thoughtful everyday.`,
    },
];

export const directories: DirectoryEntry[] = [
    {
        id: `interface-index`,
        initials: `Ii`,
        accent: `blue`,
        featured: true,
        category: `design`,
        name: `Interface Index`,
        label: `Interfaces & inspiration`,
        summary: `Thoughtful interfaces, useful patterns, and the details that make digital products feel right.`,
    },
    {
        id: `maker-stack`,
        initials: `Ms`,
        accent: `ink`,
        featured: true,
        category: `tools`,
        name: `Maker Stack`,
        label: `Tools for builders`,
        summary: `A considered collection of tools for turning a side project into something you can share.`,
    },
    {
        id: `common-ground`,
        initials: `Cg`,
        accent: `green`,
        featured: true,
        category: `communities`,
        name: `Common Ground`,
        label: `Creative communities`,
        summary: `Find your people in welcoming communities for designers, makers, and curious minds.`,
    },
    {
        id: `city-field-notes`,
        initials: `Cf`,
        accent: `red`,
        featured: false,
        category: `places`,
        name: `City Field Notes`,
        label: `Independent city guides`,
        summary: `Local discoveries, neighborhood favorites, and independent guides to a better day out.`,
    },
    {
        id: `type-foundry`,
        initials: `Tf`,
        accent: `ink`,
        featured: false,
        category: `design`,
        name: `Type Foundry`,
        label: `Type & typography`,
        summary: `Explore independent type foundries, distinctive letterforms, and resources for setting better type.`,
    },
    {
        id: `open-toolbox`,
        initials: `Ot`,
        accent: `blue`,
        featured: false,
        category: `tools`,
        name: `Open Toolbox`,
        label: `Open source essentials`,
        summary: `Practical open source tools that make everyday creative work a little more enjoyable.`,
    },
    {
        id: `project-people`,
        initials: `Pp`,
        accent: `red`,
        featured: false,
        category: `communities`,
        name: `Project People`,
        label: `Collaborators & collectives`,
        summary: `Independent collectives and spaces where a shared interest can become a shared project.`,
    },
    {
        id: `open-atlas`,
        initials: `Oa`,
        accent: `green`,
        featured: false,
        category: `places`,
        name: `Open Atlas`,
        label: `Spaces worth exploring`,
        summary: `A starting point for discovering studios, public spaces, and corners of the world with character.`,
    },
    {
        id: `form-and-function`,
        initials: `Ff`,
        accent: `blue`,
        featured: false,
        category: `design`,
        name: `Form & Function`,
        label: `Design systems & resources`,
        summary: `Design systems, accessible resources, and useful building blocks for your next good idea.`,
    },
    {
        id: `curiosity-classroom`,
        initials: `Cc`,
        accent: `yellow`,
        featured: false,
        category: `learning`,
        name: `Curiosity Classroom`,
        label: `Courses & learning resources`,
        summary: `A sample collection of courses, reading lists, and resources for learning something new.`,
    },
    {
        id: `future-files`,
        initials: `Ff`,
        accent: `purple`,
        featured: false,
        category: `technology`,
        name: `Future Files`,
        label: `Technology & emerging ideas`,
        summary: `A sample starting point for exploring new technology, useful experiments, and emerging ideas.`,
    },
    {
        id: `independent-playbook`,
        initials: `Ip`,
        accent: `orange`,
        featured: false,
        category: `business`,
        name: `Independent Playbook`,
        label: `Small business & entrepreneurship`,
        summary: `A sample directory of practical resources for independent businesses and people getting started.`,
    },
    {
        id: `everyday-edit`,
        initials: `Ee`,
        accent: `pink`,
        featured: false,
        category: `lifestyle`,
        name: `Everyday Edit`,
        label: `Lifestyle & everyday inspiration`,
        summary: `A sample collection of everyday inspiration, thoughtful habits, and little things worth finding.`,
    },
    {
        id: `product-hunt`,
        initials: `Ph`,
        accent: `orange`,
        featured: true,
        category: `technology`,
        name: `Product Hunt`,
        label: `New products & launches`,
        href: `https://www.producthunt.com/`,
        summary: `Find new products, tools, and ideas shared by makers and their communities.`,
    },
    {
        id: `alternative-to`,
        initials: `At`,
        accent: `green`,
        featured: false,
        category: `tools`,
        name: `AlternativeTo`,
        label: `Software alternatives`,
        href: `https://alternativeto.net/`,
        summary: `Compare community recommended alternatives to the apps and services you use.`,
    },
    {
        id: `awwwards`,
        initials: `Aw`,
        accent: `red`,
        featured: true,
        category: `design`,
        name: `Awwwards`,
        label: `Website inspiration`,
        href: `https://www.awwwards.com/`,
        summary: `Browse recognized websites and creative work from designers around the world.`,
    },
    {
        id: `behance`,
        initials: `Be`,
        accent: `blue`,
        featured: false,
        category: `communities`,
        name: `Behance`,
        label: `Creative portfolios`,
        href: `https://www.behance.net/`,
        summary: `Explore portfolios and projects shared by a global creative community.`,
    },
    {
        id: `g2`,
        initials: `G2`,
        accent: `purple`,
        featured: false,
        category: `business`,
        name: `G2`,
        label: `Business software reviews`,
        href: `https://www.g2.com/`,
        summary: `Find and compare business software using product listings and reviews.`,
    },
    {
        id: `yelp`,
        initials: `Ye`,
        accent: `pink`,
        featured: false,
        category: `places`,
        name: `Yelp`,
        label: `Local places & services`,
        href: `https://www.yelp.com/`,
        summary: `Discover local restaurants, shops, and services through community reviews.`,
    },
    {
        id: `all-trails`,
        initials: `At`,
        accent: `green`,
        featured: false,
        category: `lifestyle`,
        name: `AllTrails`,
        label: `Trails & outdoor places`,
        href: `https://www.alltrails.com/`,
        summary: `Explore trails, parks, and routes for your next time outdoors.`,
    },
    {
        id: `open-library`,
        initials: `Ol`,
        accent: `yellow`,
        featured: false,
        category: `learning`,
        name: `Open Library`,
        label: `Books & reading`,
        href: `https://openlibrary.org/`,
        summary: `Search an open catalog of books, authors, and reading resources.`,
    },
    {
        id: `mobbin`,
        initials: `Mo`,
        accent: `blue`,
        featured: true,
        category: `design`,
        name: `Mobbin`,
        label: `App design patterns`,
        href: `https://mobbin.com/`,
        summary: `Search real app screens, interface elements, and product flows for design reference.`,
    },
    {
        id: `siteinspire`,
        initials: `Si`,
        accent: `pink`,
        featured: false,
        category: `design`,
        name: `Siteinspire`,
        label: `Curated websites`,
        href: `https://www.siteinspire.com/`,
        summary: `Browse a curated gallery of websites and the designers behind them.`,
    },
    {
        id: `futurepedia`,
        initials: `Fu`,
        accent: `purple`,
        featured: false,
        category: `tools`,
        name: `Futurepedia`,
        label: `AI tools by category`,
        href: `https://www.futurepedia.io/`,
        summary: `Explore categorized AI tools for creative work, productivity, and research.`,
    },
    {
        id: `open-alternative`,
        initials: `Oa`,
        accent: `green`,
        featured: false,
        category: `tools`,
        name: `OpenAlternative`,
        label: `Open source alternatives`,
        href: `https://openalternative.co/`,
        summary: `Find open source replacements for popular software and services.`,
    },
    {
        id: `meetup`,
        initials: `Me`,
        accent: `red`,
        featured: false,
        category: `communities`,
        name: `Meetup`,
        label: `Groups & events`,
        href: `https://www.meetup.com/`,
        summary: `Find local groups and events built around shared interests.`,
    },
    {
        id: `atlas-obscura`,
        initials: `Ao`,
        accent: `ink`,
        featured: false,
        category: `places`,
        name: `Atlas Obscura`,
        label: `Unusual places`,
        href: `https://www.atlasobscura.com/`,
        summary: `Discover remarkable destinations and lesser known places around the world.`,
    },
    {
        id: `class-central`,
        initials: `Cc`,
        accent: `yellow`,
        featured: true,
        category: `learning`,
        name: `Class Central`,
        label: `Online courses`,
        href: `https://www.classcentral.com/`,
        summary: `Search online courses across universities and learning providers.`,
    },
    {
        id: `hugging-face-spaces`,
        initials: `Hs`,
        accent: `orange`,
        featured: false,
        category: `technology`,
        name: `Hugging Face Spaces`,
        label: `AI app directory`,
        href: `https://huggingface.co/spaces`,
        summary: `Browse interactive AI apps and demos shared by the developer community.`,
    },
    {
        id: `crunchbase`,
        initials: `Cr`,
        accent: `blue`,
        featured: false,
        category: `business`,
        name: `Crunchbase`,
        label: `Company discovery`,
        href: `https://www.crunchbase.com/`,
        summary: `Explore company profiles, funding information, and market activity.`,
    },
    {
        id: `good-on-you`,
        initials: `Gy`,
        accent: `green`,
        featured: false,
        category: `lifestyle`,
        name: `Good On You`,
        label: `Fashion brand ratings`,
        href: `https://goodonyou.eco/`,
        summary: `Look up fashion and beauty brands through sustainability ratings and guides.`,
    },
];

export const linkedDirectories = directories.filter(
    (directory): directory is DirectoryEntry & { href: string } => Boolean(directory.href),
);
