import type { IconName } from '../../components/Icon/Icon.types';

export type CategoryId =
    | `ai`
    | `auto`
    | `news`
    | `adult`
    | `health`
    | `travel`
    | `creative`
    | `business`
    | `learning`
    | `community`
    | `entertainment`
    | `professionals`;
export type DirectoryAccent = `ink` | `red` | `blue` | `pink` | `green` | `yellow` | `purple` | `orange`;
export type DirectoryStatusId = `new` | `top` | `best` | `local` | `popular` | `trending` | `regional` | `national` | `international`;
export type DirectoryCategoryIcon = `tools` | `design` | `places` | `learning` | `business` | `lifestyle` | `file-text` | `technology` | `communities` | `clapperboard`;

export interface DirectoryStatus {
    icon: IconName;
    label: string;
    description: string;
    id: DirectoryStatusId;
    tone: `green` | `gray` | `red`;
}

export interface DirectoryCategory {
    id: CategoryId;
    label: string;
    topics: string[];
    description: string;
    accent: DirectoryAccent;
    icon: DirectoryCategoryIcon;
}

export interface DirectoryEntry {
    id: string;
    href: string;
    name: string;
    label: string;
    topics: string[];
    summary: string;
    initials: string;
    featured: boolean;
    category: CategoryId;
    accent: DirectoryAccent;
    statuses: DirectoryStatusId[];
    previewImage?: string;
}

export const directoryStatuses: DirectoryStatus[] = [
    { id: `new`, icon: `plus`, tone: `green`, label: `New`, description: `Recently added to this collection` },
    { id: `trending`, icon: `arrow-up-right`, tone: `red`, label: `Trending`, description: `Recently popular` },
    { id: `popular`, icon: `star`, tone: `green`, label: `Popular`, description: `Consistently popular` },
    { id: `best`, icon: `trophy`, tone: `green`, label: `Best`, description: `Best all round or in all reactions` },
    { id: `top`, icon: `upvote`, tone: `red`, label: `Top`, description: `Most popular all time` },
    { id: `local`, icon: `places`, tone: `gray`, label: `Local`, description: `Local to your area` },
    { id: `regional`, icon: `map`, tone: `gray`, label: `Regional`, description: `Local to your region` },
    { id: `national`, icon: `flag`, tone: `gray`, label: `National`, description: `Local to your nation` },
    { id: `international`, icon: `globe`, tone: `gray`, label: `International`, description: `Global` },
];

export const categories: DirectoryCategory[] = [
    {
        id: `ai`,
        label: `AI`,
        accent: `blue`,
        icon: `technology`,
        description: `Discover AI agents, models, software, and tools for your next idea.`,
        topics: [`Agents`, `Models`, `Software`, `Hardware`, `Tools`, `Generation`, `Builders`, `News`],
    },
    {
        id: `business`,
        accent: `green`,
        label: `Business`,
        icon: `business`,
        description: `Find companies, careers, products, and services for building a business.`,
        topics: [
            `Careers`, `Jobs`, `Experience`, `CEOs`, `Mergers`, `Acquisitions`, `Sales`, `Ideas`, `Marketing`,
            `Finance`, `Services`, `Products`, `Payments`, `Stocks`, `Websites & Apps`, `Productivity`, `Small Business`, `Corporate`,
        ],
    },
    {
        id: `creative`,
        icon: `design`,
        accent: `purple`,
        label: `Creative`,
        description: `Explore creative work, inspiration, and resources for making something new.`,
        topics: [`Art`, `Writing`, `Reading`, `Design`, `Animation`, `Drawing`, `Video`, `Music`, `Photo`, `Development`, `Beauty`, `Production`],
    },
    {
        accent: `pink`,
        id: `entertainment`,
        icon: `clapperboard`,
        label: `Entertainment`,
        description: `Find movies, shows, music, games, and the people behind them.`,
        topics: [
            `Humor`, `Movies`, `TV Shows`, `Horror`, `Celebrities`, `Hollywood`, `Bollywood`,
            `K-Dramas`, `K-Pop`, `Music`, `Gaming`, `Sports`, `Box Office`,
        ],
    },
    {
        id: `news`,
        label: `News`,
        accent: `red`,
        icon: `file-text`,
        description: `Browse news sources, current events, research, and public data.`,
        topics: [`Politics`, `Government`, `Weather`, `Science`, `History`, `Current Events`, `Local Events`, `War`, `Debates`, `Books`, `Articles`, `Data`, `Charts`],
    },
    {
        id: `health`,
        label: `Health`,
        accent: `green`,
        icon: `lifestyle`,
        description: `Explore health information, wellness resources, and ways to stay active.`,
        topics: [`Biological`, `Mental`, `Dental`, `Insurance`, `Wellness`, `Motivation`, `Nutrition`, `Fitness`, `Disease`, `Outbreaks`, `Policy`],
    },
    {
        id: `auto`,
        label: `Auto`,
        icon: `tools`,
        accent: `orange`,
        description: `Browse vehicles, automotive resources, and transport options.`,
        topics: [`Cars`, `Used Cars`, `Maintenance`, `Concepts`, `Driving`, `Motorcycles`, `Airplanes`, `Trains`, `Rentals`],
    },
    {
        id: `learning`,
        accent: `yellow`,
        label: `Learning`,
        icon: `learning`,
        description: `Find courses, books, and educational resources for curious minds.`,
        topics: [`Students`, `Teachers`, `Projects`, `Science`, `Math`, `Skills`, `Trades`, `Coaching`, `Mentoring`, `Testing`],
    },
    {
        id: `travel`,
        accent: `ink`,
        icon: `places`,
        label: `Travel`,
        description: `Discover destinations, places to stay, and ideas for your next trip.`,
        topics: [`Vacations`, `Family Trips`, `Planners`, `Flights`, `Stays`, `Rentals`],
    },
    {
        accent: `blue`,
        icon: `business`,
        id: `professionals`,
        label: `Professionals`,
        description: `Find healthcare and legal professionals by specialty and location.`,
        topics: [`Doctors`, `Lawyers`, `Therapists`, `Dentists`],
    },
    {
        accent: `green`,
        id: `community`,
        label: `Community`,
        icon: `communities`,
        description: `Connect with local groups, events, organizations, and community resources.`,
        topics: [`Events`, `Leaders`, `Churches`, `Religious Sites`, `Culture`, `Government`, `Legal`, `Policing`, `Crime`],
    },
    {
        id: `adult`,
        label: `Adult`,
        accent: `purple`,
        icon: `lifestyle`,
        description: `Explore dating, relationships, sexual wellness, and educational resources for adults.`,
        topics: [`Dating`, `Relationships`, `Sexual Wellness`, `Education`, `Therapists`, `Communities`],
    },
];

export const directories: DirectoryEntry[] = [
    {
        id: `futurepedia`,
        initials: `Fu`,
        category: `ai`,
        accent: `purple`,
        featured: true,
        name: `Futurepedia`,
        label: `AI tools by category`,
        topics: [`Tools`, `Generation`],
        statuses: [`international`],
        href: `https://www.futurepedia.io/`,
        previewImage: `/directory-previews/futurepedia.webp`,
        summary: `Explore categorized AI tools for creative work, productivity, and research.`,
    },
    {
        initials: `Hs`,
        category: `ai`,
        accent: `orange`,
        featured: false,
        id: `hugging-face-spaces`,
        label: `AI app directory`,
        statuses: [`international`],
        name: `Hugging Face Spaces`,
        topics: [`Models`, `Generation`, `Builders`],
        href: `https://huggingface.co/spaces`,
        previewImage: `/directory-previews/hugging-face-spaces.webp`,
        summary: `Browse interactive AI apps and demos shared by the developer community.`,
    },
    {
        initials: `At`,
        category: `ai`,
        accent: `green`,
        featured: false,
        id: `alternative-to`,
        name: `AlternativeTo`,
        topics: [`Tools`, `Software`],
        label: `Software alternatives`,
        statuses: [`international`],
        href: `https://alternativeto.net/`,
        previewImage: `/directory-previews/alternative-to.webp`,
        summary: `Compare community recommended alternatives to the apps and services you use.`,
    },
    {
        initials: `Oa`,
        category: `ai`,
        accent: `green`,
        featured: false,
        id: `open-alternative`,
        name: `OpenAlternative`,
        topics: [`Tools`, `Software`],
        statuses: [`international`],
        label: `Open source alternatives`,
        href: `https://openalternative.co/`,
        previewImage: `/directory-previews/open-alternative.webp`,
        summary: `Find open source replacements for popular software and services.`,
    },
    {
        initials: `Ad`,
        category: `ai`,
        accent: `blue`,
        featured: false,
        id: `ai-tools-directory`,
        name: `AI Tools Directory`,
        label: `Curated AI software`,
        topics: [`Tools`, `Software`, `Generation`],
        statuses: [`new`, `international`],
        href: `https://aitoolsdirectory.com/`,
        previewImage: `/directory-previews/ai-tools-directory.webp`,
        summary: `Browse AI tools by category and use case for writing, design, coding, and everyday work.`,
    },
    {
        initials: `Aa`,
        category: `ai`,
        accent: `red`,
        featured: false,
        id: `ai-agents-directory`,
        name: `AI Agents Directory`,
        topics: [`Agents`, `Builders`],
        label: `Agents & frameworks`,
        statuses: [`new`, `international`],
        href: `https://aiagentsdirectory.com/`,
        previewImage: `/directory-previews/ai-agents-directory.webp`,
        summary: `Discover AI agents and frameworks organized by workflow, category, and use case.`,
    },
    {
        initials: `Hm`,
        category: `ai`,
        accent: `yellow`,
        featured: false,
        id: `hugging-face-models`,
        topics: [`Models`, `Builders`],
        name: `Hugging Face Models`,
        label: `Machine learning models`,
        statuses: [`new`, `international`],
        href: `https://huggingface.co/models`,
        previewImage: `/directory-previews/hugging-face-models.webp`,
        summary: `Find machine learning models by task, library, language, and license.`,
    },
    {
        id: `product-hunt`,
        initials: `Ph`,
        accent: `orange`,
        featured: true,
        category: `business`,
        name: `Product Hunt`,
        statuses: [`international`],
        label: `New products & launches`,
        topics: [`Ideas`, `Products`, `Websites & Apps`],
        href: `https://www.producthunt.com/`,
        previewImage: `/directory-previews/product-hunt.webp`,
        summary: `Find new products, tools, and ideas shared by makers and their communities.`,
    },
    {
        id: `g2`,
        initials: `G2`,
        name: `G2`,
        accent: `purple`,
        featured: false,
        category: `business`,
        statuses: [`international`],
        label: `Business software reviews`,
        topics: [`Products`, `Services`, `Websites & Apps`],
        href: `https://www.g2.com/`,
        summary: `Find and compare business software using product listings and reviews.`,
    },
    {
        id: `crunchbase`,
        initials: `Cr`,
        accent: `blue`,
        featured: false,
        name: `Crunchbase`,
        category: `business`,
        label: `Company discovery`,
        statuses: [`international`],
        topics: [`CEOs`, `Finance`, `Corporate`],
        href: `https://www.crunchbase.com/`,
        previewImage: `/directory-previews/crunchbase.webp`,
        summary: `Explore company profiles, funding information, and market activity.`,
    },
    {
        id: `capterra`,
        initials: `Ca`,
        accent: `orange`,
        featured: false,
        name: `Capterra`,
        category: `business`,
        label: `Software comparisons`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Small Business`],
        href: `https://www.capterra.com/`,
        summary: `Browse business software categories and compare features, pricing, and verified user reviews.`,
    },
    {
        id: `getapp`,
        initials: `Ga`,
        name: `GetApp`,
        accent: `green`,
        featured: false,
        category: `business`,
        label: `Apps for businesses`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Websites & Apps`],
        href: `https://www.getapp.com/`,
        summary: `Explore business applications by category with product comparisons and customer reviews.`,
    },
    {
        id: `clutch`,
        initials: `Cl`,
        name: `Clutch`,
        accent: `red`,
        featured: false,
        category: `business`,
        label: `Business service providers`,
        statuses: [`new`, `international`],
        topics: [`Services`, `Marketing`, `Small Business`],
        href: `https://clutch.co/`,
        summary: `Find agencies and business service providers through detailed profiles and client reviews.`,
    },
    {
        id: `saashub`,
        initials: `Sh`,
        name: `SaaSHub`,
        accent: `blue`,
        featured: false,
        category: `business`,
        label: `Software & startup discovery`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Websites & Apps`],
        href: `https://www.saashub.com/`,
        previewImage: `/directory-previews/saashub.webp`,
        summary: `Discover software alternatives, startup products, and tools organized by business needs.`,
    },
    {
        id: `awwwards`,
        initials: `Aw`,
        accent: `red`,
        featured: true,
        name: `Awwwards`,
        category: `creative`,
        label: `Website inspiration`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://www.awwwards.com/`,
        previewImage: `/directory-previews/awwwards.webp`,
        summary: `Browse recognized websites and creative work from designers around the world.`,
    },
    {
        id: `behance`,
        initials: `Be`,
        accent: `blue`,
        featured: false,
        name: `Behance`,
        category: `creative`,
        topics: [`Art`, `Design`, `Photo`],
        label: `Creative portfolios`,
        statuses: [`international`],
        href: `https://www.behance.net/`,
        previewImage: `/directory-previews/behance.webp`,
        summary: `Explore portfolios and projects shared by a global creative community.`,
    },
    {
        id: `mobbin`,
        initials: `Mo`,
        name: `Mobbin`,
        accent: `blue`,
        featured: true,
        category: `creative`,
        label: `App design patterns`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://mobbin.com/`,
        previewImage: `/directory-previews/mobbin.webp`,
        summary: `Search real app screens, interface elements, and product flows for design reference.`,
    },
    {
        id: `siteinspire`,
        initials: `Si`,
        accent: `pink`,
        featured: false,
        name: `Siteinspire`,
        category: `creative`,
        label: `Curated websites`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://www.siteinspire.com/`,
        summary: `Browse a curated gallery of websites and the designers behind them.`,
    },
    {
        id: `good-on-you`,
        initials: `Gy`,
        accent: `green`,
        featured: false,
        name: `Good On You`,
        category: `creative`,
        topics: [`Beauty`, `Design`],
        label: `Fashion brand ratings`,
        statuses: [`international`],
        href: `https://directory.goodonyou.eco/`,
        summary: `Look up fashion and beauty brands through sustainability ratings and guides.`,
    },
    {
        id: `google-fonts`,
        initials: `Gf`,
        accent: `blue`,
        featured: false,
        name: `Google Fonts`,
        category: `creative`,
        topics: [`Design`, `Development`],
        label: `Fonts & typography`,
        statuses: [`new`, `international`],
        href: `https://fonts.google.com/`,
        previewImage: `/directory-previews/google-fonts.webp`,
        summary: `Browse font families and typography resources for websites and creative projects.`,
    },
    {
        id: `dribbble`,
        initials: `Dr`,
        accent: `pink`,
        featured: false,
        name: `Dribbble`,
        category: `creative`,
        topics: [`Art`, `Design`, `Animation`],
        label: `Designers & design inspiration`,
        statuses: [`new`, `international`],
        href: `https://dribbble.com/`,
        previewImage: `/directory-previews/dribbble.webp`,
        summary: `Explore visual design work and discover creative professionals by specialty.`,
    },
    {
        id: `artstation`,
        initials: `As`,
        accent: `ink`,
        featured: false,
        name: `ArtStation`,
        category: `creative`,
        label: `Artists & digital portfolios`,
        statuses: [`new`, `international`],
        topics: [`Art`, `Drawing`, `Animation`],
        href: `https://www.artstation.com/`,
        summary: `Discover digital art, illustrations, and portfolios from artists working in games, film, and beyond.`,
    },
    {
        initials: `Ao`,
        accent: `blue`,
        featured: true,
        category: `creative`,
        topics: [`Development`],
        id: `awesome-open-source`,
        name: `Awesome Open Source`,
        label: `Open source project directory`,
        statuses: [`new`, `international`],
        href: `https://awesomeopensource.com/`,
        summary: `Find and compare open source projects by category, programming language, and package.`,
    },
    {
        id: `imdb`,
        initials: `Im`,
        name: `IMDb`,
        accent: `yellow`,
        featured: true,
        category: `entertainment`,
        label: `Movies, shows & people`,
        statuses: [`new`, `international`],
        topics: [`Movies`, `TV Shows`, `Celebrities`],
        href: `https://www.imdb.com/`,
        summary: `Search movie and television titles, cast and crew profiles, reviews, and viewing information.`,
    },
    {
        id: `tmdb`,
        initials: `Tm`,
        accent: `green`,
        featured: false,
        name: `The Movie Database`,
        category: `entertainment`,
        topics: [`Movies`, `TV Shows`],
        label: `Community movie & TV catalog`,
        statuses: [`new`, `international`],
        href: `https://www.themoviedb.org/`,
        previewImage: `/directory-previews/tmdb.webp`,
        summary: `Explore a community maintained database of movies, television shows, actors, and artwork.`,
    },
    {
        id: `letterboxd`,
        initials: `Lb`,
        accent: `orange`,
        featured: false,
        name: `Letterboxd`,
        category: `entertainment`,
        topics: [`Movies`, `Horror`],
        label: `Film discovery & lists`,
        statuses: [`new`, `international`],
        href: `https://letterboxd.com/`,
        summary: `Discover films through member reviews, watchlists, and collections from a film community.`,
    },
    {
        id: `igdb`,
        initials: `Ig`,
        name: `IGDB`,
        accent: `purple`,
        featured: false,
        topics: [`Gaming`],
        category: `entertainment`,
        label: `Video game database`,
        statuses: [`new`, `international`],
        href: `https://www.igdb.com/`,
        summary: `Browse video games, genres, platforms, release information, and community ratings.`,
    },
    {
        id: `musicbrainz`,
        initials: `Mb`,
        accent: `orange`,
        featured: false,
        name: `MusicBrainz`,
        topics: [`Music`],
        category: `entertainment`,
        label: `Open music encyclopedia`,
        statuses: [`new`, `international`],
        href: `https://musicbrainz.org/`,
        summary: `Explore an open catalog of artists, recordings, releases, and related music information.`,
    },
    {
        id: `allsides`,
        initials: `As`,
        category: `news`,
        accent: `purple`,
        featured: false,
        name: `AllSides`,
        label: `News source perspectives`,
        statuses: [`new`, `national`],
        topics: [`Politics`, `Debates`, `Articles`],
        href: `https://www.allsides.com/media-bias`,
        summary: `Browse news sources and media bias ratings to compare perspectives on current events.`,
    },
    {
        id: `ground-news`,
        initials: `Gn`,
        category: `news`,
        accent: `ink`,
        featured: false,
        name: `Ground News`,
        label: `News source comparison`,
        statuses: [`new`, `international`],
        topics: [`Politics`, `Current Events`, `Local Events`],
        href: `https://ground.news/`,
        previewImage: `/directory-previews/ground-news.webp`,
        summary: `Compare coverage across news sources and browse stories by topic or location.`,
    },
    {
        id: `data-gov`,
        initials: `Dg`,
        category: `news`,
        accent: `blue`,
        featured: false,
        name: `Data.gov`,
        label: `Public data catalog`,
        statuses: [`new`, `national`],
        topics: [`Data`, `Science`],
        href: `https://catalog.data.gov/`,
        previewImage: `/directory-previews/data-gov.webp`,
        summary: `Search public datasets from United States government agencies and participating organizations.`,
    },
    {
        initials: `Ow`,
        category: `news`,
        accent: `red`,
        featured: false,
        id: `our-world-in-data`,
        name: `Our World in Data`,
        label: `Research, data & charts`,
        statuses: [`new`, `international`],
        topics: [`Data`, `Charts`, `Science`],
        href: `https://ourworldindata.org/`,
        previewImage: `/directory-previews/our-world-in-data.webp`,
        summary: `Explore research topics, datasets, and charts covering global conditions and long term change.`,
    },
    {
        id: `all-trails`,
        initials: `At`,
        accent: `green`,
        featured: false,
        category: `health`,
        name: `AllTrails`,
        topics: [`Fitness`, `Wellness`],
        label: `Trails & outdoor places`,
        statuses: [`local`, `international`],
        href: `https://www.alltrails.com/`,
        previewImage: `/directory-previews/all-trails.webp`,
        summary: `Explore trails, parks, and routes for your next time outdoors.`,
    },
    {
        id: `medlineplus`,
        initials: `Mp`,
        accent: `blue`,
        featured: false,
        category: `health`,
        name: `MedlinePlus`,
        label: `Health topic library`,
        statuses: [`new`, `national`],
        topics: [`Disease`, `Wellness`, `Biological`],
        href: `https://medlineplus.gov/healthtopics.html`,
        previewImage: `/directory-previews/medlineplus.webp`,
        summary: `Browse health topics with information from the United States National Library of Medicine.`,
    },
    {
        initials: `Nh`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `nhs-conditions`,
        name: `NHS Conditions`,
        label: `Conditions A to Z`,
        statuses: [`new`, `national`],
        topics: [`Disease`, `Mental`, `Dental`],
        href: `https://www.nhs.uk/conditions/`,
        previewImage: `/directory-previews/nhs-conditions.webp`,
        summary: `Find National Health Service information about health conditions, symptoms, and care in the UK.`,
    },
    {
        id: `nutrition-gov`,
        initials: `Ng`,
        accent: `green`,
        featured: false,
        category: `health`,
        name: `Nutrition.gov`,
        topics: [`Nutrition`, `Wellness`],
        label: `Food & nutrition resources`,
        statuses: [`new`, `national`],
        href: `https://www.nutrition.gov/topics`,
        previewImage: `/directory-previews/nutrition-gov.webp`,
        summary: `Browse United States government nutrition resources by topic and stage of life.`,
    },
    {
        initials: `Mh`,
        accent: `green`,
        featured: false,
        category: `health`,
        id: `mental-health-america`,
        name: `Mental Health America`,
        topics: [`Mental`, `Wellness`, `Policy`],
        label: `Mental health resource library`,
        statuses: [`new`, `national`],
        href: `https://mhanational.org/resources/`,
        previewImage: `/directory-previews/mental-health-america.webp`,
        summary: `Explore mental health guides, fact sheets, and support resources from a national nonprofit.`,
    },
    {
        id: `autotrader`,
        initials: `Au`,
        category: `auto`,
        accent: `blue`,
        featured: false,
        name: `Autotrader`,
        label: `New & used car listings`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.autotrader.com/`,
        summary: `Search new and used vehicles from dealerships and private sellers in the United States.`,
    },
    {
        id: `cars-com`,
        initials: `Ca`,
        category: `auto`,
        accent: `purple`,
        featured: false,
        name: `Cars.com`,
        label: `Cars, dealers & research`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.cars.com/`,
        summary: `Compare vehicle listings, dealership profiles, reviews, and car research in the United States.`,
    },
    {
        id: `cargurus`,
        initials: `Cg`,
        category: `auto`,
        accent: `blue`,
        featured: false,
        name: `CarGurus`,
        label: `Vehicle & dealer discovery`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.cargurus.com/`,
        previewImage: `/directory-previews/cargurus.webp`,
        summary: `Find vehicle listings and compare asking prices, deal information, and sellers.`,
    },
    {
        initials: `Bt`,
        category: `auto`,
        accent: `yellow`,
        featured: false,
        id: `bring-a-trailer`,
        name: `Bring a Trailer`,
        label: `Classic & enthusiast auctions`,
        topics: [`Cars`, `Used Cars`, `Motorcycles`],
        statuses: [`new`, `international`],
        href: `https://bringatrailer.com/`,
        previewImage: `/directory-previews/bring-a-trailer.webp`,
        summary: `Browse curated vehicle auctions, past listings, and discussion from an enthusiast community.`,
    },
    {
        id: `cars-and-bids`,
        initials: `Cb`,
        category: `auto`,
        accent: `green`,
        featured: false,
        name: `Cars & Bids`,
        label: `Modern enthusiast car auctions`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `national`],
        href: `https://carsandbids.com/`,
        previewImage: `/directory-previews/cars-and-bids.webp`,
        summary: `Discover auctions for modern enthusiast cars, trucks, and SUVs with detailed listing information.`,
    },
    {
        id: `class-central`,
        initials: `Cc`,
        accent: `yellow`,
        featured: true,
        category: `learning`,
        name: `Class Central`,
        label: `Online courses`,
        topics: [`Skills`, `Students`, `Science`],
        statuses: [`international`],
        href: `https://www.classcentral.com/`,
        previewImage: `/directory-previews/class-central.webp`,
        summary: `Search online courses across universities and learning providers.`,
    },
    {
        id: `open-library`,
        initials: `Ol`,
        accent: `yellow`,
        featured: false,
        category: `learning`,
        name: `Open Library`,
        topics: [`Students`, `Teachers`],
        label: `Books & reading`,
        statuses: [`international`],
        href: `https://openlibrary.org/`,
        summary: `Search an open catalog of books, authors, and reading resources.`,
    },
    {
        id: `merlot`,
        initials: `Me`,
        name: `MERLOT`,
        accent: `green`,
        featured: false,
        category: `learning`,
        label: `Learning materials & resources`,
        statuses: [`new`, `international`],
        topics: [`Students`, `Teachers`, `Skills`],
        href: `https://www.merlot.org/merlot/`,
        previewImage: `/directory-previews/merlot.webp`,
        summary: `Find curated learning materials and resources contributed by educators and institutions.`,
    },
    {
        initials: `Oc`,
        accent: `red`,
        featured: false,
        id: `mit-opencourseware`,
        category: `learning`,
        name: `MIT OpenCourseWare`,
        label: `Open university course materials`,
        statuses: [`new`, `international`],
        topics: [`Math`, `Science`, `Students`],
        href: `https://ocw.mit.edu/`,
        previewImage: `/directory-previews/mit-opencourseware.webp`,
        summary: `Browse free course materials from Massachusetts Institute of Technology classes by subject.`,
    },
    {
        id: `oer-commons`,
        initials: `Oc`,
        accent: `blue`,
        featured: false,
        category: `learning`,
        name: `OER Commons`,
        label: `Open educational resources`,
        statuses: [`new`, `international`],
        topics: [`Projects`, `Teachers`, `Students`],
        href: `https://oercommons.org/`,
        previewImage: `/directory-previews/oer-commons.webp`,
        summary: `Discover open teaching and learning materials by subject, education level, and resource type.`,
    },
    {
        id: `yelp`,
        initials: `Ye`,
        name: `Yelp`,
        accent: `pink`,
        featured: false,
        category: `travel`,
        topics: [`Planners`, `Family Trips`],
        label: `Local places & services`,
        statuses: [`local`, `regional`],
        href: `https://www.yelp.com/`,
        summary: `Discover local restaurants, shops, and services through community reviews.`,
    },
    {
        id: `atlas-obscura`,
        initials: `Ao`,
        accent: `ink`,
        featured: false,
        category: `travel`,
        name: `Atlas Obscura`,
        label: `Unusual places`,
        statuses: [`international`],
        topics: [`Vacations`, `Planners`, `Family Trips`],
        href: `https://www.atlasobscura.com/`,
        previewImage: `/directory-previews/atlas-obscura.webp`,
        summary: `Discover remarkable destinations and lesser known places around the world.`,
    },
    {
        id: `booking-com`,
        initials: `Bc`,
        accent: `blue`,
        featured: false,
        category: `travel`,
        name: `Booking.com`,
        label: `Stays & travel bookings`,
        statuses: [`new`, `international`],
        topics: [`Stays`, `Flights`, `Rentals`],
        href: `https://www.booking.com/`,
        previewImage: `/directory-previews/booking-com.webp`,
        summary: `Discover accommodation, flights, and rental options for destinations around the world.`,
    },
    {
        id: `tripadvisor`,
        initials: `Ta`,
        accent: `green`,
        featured: false,
        category: `travel`,
        name: `Tripadvisor`,
        label: `Places, stays & traveler reviews`,
        statuses: [`new`, `local`, `international`],
        topics: [`Stays`, `Planners`, `Vacations`],
        href: `https://www.tripadvisor.com/`,
        summary: `Explore hotels, restaurants, attractions, and experiences with reviews from travelers.`,
    },
    {
        id: `wikivoyage`,
        initials: `Wv`,
        accent: `blue`,
        featured: false,
        category: `travel`,
        name: `Wikivoyage`,
        label: `Open destination guides`,
        statuses: [`new`, `international`],
        topics: [`Planners`, `Vacations`, `Family Trips`],
        href: `https://en.wikivoyage.org/wiki/Main_Page`,
        previewImage: `/directory-previews/wikivoyage.webp`,
        summary: `Browse collaboratively written destination guides and practical travel information.`,
    },
    {
        id: `healthgrades`,
        initials: `Hg`,
        accent: `blue`,
        featured: false,
        name: `Healthgrades`,
        category: `professionals`,
        topics: [`Doctors`, `Dentists`],
        label: `Doctors & healthcare facilities`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.healthgrades.com/`,
        previewImage: `/directory-previews/healthgrades.webp`,
        summary: `Find United States doctors, dentists, hospitals, and healthcare professionals by specialty and location.`,
    },
    {
        id: `zocdoc`,
        initials: `Zo`,
        name: `Zocdoc`,
        accent: `yellow`,
        featured: false,
        category: `professionals`,
        label: `Healthcare providers & appointments`,
        topics: [`Doctors`, `Dentists`, `Therapists`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.zocdoc.com/`,
        summary: `Discover United States healthcare providers and appointment options by specialty, location, and insurance.`,
    },
    {
        initials: `Pt`,
        accent: `green`,
        featured: false,
        id: `psychology-today`,
        name: `Psychology Today`,
        topics: [`Therapists`],
        category: `professionals`,
        label: `Therapist directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.psychologytoday.com/us/therapists`,
        previewImage: `/directory-previews/psychology-today.webp`,
        summary: `Search United States therapist profiles by location, specialty, and treatment approach.`,
    },
    {
        id: `avvo`,
        initials: `Av`,
        name: `Avvo`,
        accent: `blue`,
        featured: false,
        topics: [`Lawyers`],
        category: `professionals`,
        label: `Lawyers & legal help`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.avvo.com/`,
        previewImage: `/directory-previews/avvo.webp`,
        summary: `Find United States attorneys by practice area and location with profiles and client reviews.`,
    },
    {
        id: `findlaw`,
        initials: `Fl`,
        name: `FindLaw`,
        accent: `orange`,
        featured: false,
        topics: [`Lawyers`],
        category: `professionals`,
        label: `Attorney directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://lawyers.findlaw.com/`,
        previewImage: `/directory-previews/findlaw.webp`,
        summary: `Browse United States lawyers and law firms by legal issue and location.`,
    },
    {
        id: `meetup`,
        initials: `Me`,
        name: `Meetup`,
        accent: `red`,
        featured: true,
        category: `community`,
        label: `Groups & events`,
        topics: [`Events`, `Culture`],
        statuses: [`local`, `regional`, `international`],
        href: `https://www.meetup.com/`,
        previewImage: `/directory-previews/meetup.webp`,
        summary: `Find local groups and events built around shared interests.`,
    },
    {
        id: `idealist`,
        initials: `Id`,
        name: `Idealist`,
        accent: `blue`,
        featured: false,
        category: `community`,
        label: `Nonprofits & volunteering`,
        statuses: [`new`, `local`, `international`],
        topics: [`Events`, `Leaders`, `Culture`],
        href: `https://www.idealist.org/en`,
        previewImage: `/directory-previews/idealist.webp`,
        summary: `Discover nonprofit organizations, volunteer opportunities, events, and ways to support communities.`,
    },
    {
        id: `findhelp`,
        initials: `Fh`,
        name: `findhelp`,
        accent: `green`,
        featured: false,
        category: `community`,
        label: `Community support programs`,
        topics: [`Legal`, `Government`],
        statuses: [`new`, `local`, `regional`, `national`],
        href: `https://www.findhelp.org/`,
        previewImage: `/directory-previews/findhelp.webp`,
        summary: `Search United States community programs offering free or reduced cost support by ZIP code.`,
    },
    {
        id: `guidestar`,
        initials: `Gs`,
        name: `GuideStar`,
        accent: `blue`,
        featured: false,
        category: `community`,
        topics: [`Leaders`, `Culture`],
        label: `Nonprofit organization profiles`,
        statuses: [`new`, `national`],
        href: `https://www.guidestar.org/`,
        summary: `Search United States nonprofit organizations and explore profiles, missions, and public financial information.`,
    },
    {
        id: `church-finder`,
        initials: `Cf`,
        accent: `purple`,
        featured: false,
        name: `Church Finder`,
        category: `community`,
        label: `Local church directory`,
        topics: [`Churches`, `Religious Sites`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.churchfinder.com/`,
        summary: `Find Christian churches in the United States by city, denomination, and congregation profile.`,
    },
    {
        initials: `Ms`,
        accent: `pink`,
        featured: false,
        category: `adult`,
        id: `meetup-singles`,
        name: `Meetup Singles`,
        label: `Singles groups & events`,
        statuses: [`new`, `local`, `international`],
        topics: [`Dating`, `Relationships`, `Communities`],
        href: `https://www.meetup.com/topics/singles/`,
        previewImage: `/directory-previews/meetup-singles.webp`,
        summary: `Browse singles groups and social events for meeting people with shared interests.`,
    },
    {
        id: `aasect`,
        initials: `Aa`,
        accent: `purple`,
        featured: false,
        category: `adult`,
        name: `AASECT Directory`,
        label: `Sexual wellness professionals`,
        statuses: [`new`, `international`],
        topics: [`Sexual Wellness`, `Education`, `Therapists`],
        href: `https://www.aasect.org/referral-directory`,
        previewImage: `/directory-previews/aasect.webp`,
        summary: `Find certified sexuality educators, counselors, and therapists by country or United States state.`,
    },
    {
        initials: `At`,
        accent: `blue`,
        featured: false,
        category: `adult`,
        id: `aamft-therapist-locator`,
        name: `AAMFT Therapist Locator`,
        label: `Marriage & relationship therapists`,
        topics: [`Relationships`, `Therapists`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.therapistlocator.net/`,
        previewImage: `/directory-previews/aamft-therapist-locator.webp`,
        summary: `Browse marriage and family therapists offering support for individuals, couples, and relationships.`,
    },
    {
        initials: `Pp`,
        accent: `pink`,
        featured: false,
        category: `adult`,
        id: `planned-parenthood`,
        topics: [`Sexual Wellness`],
        name: `Planned Parenthood`,
        label: `Sexual health center directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.plannedparenthood.org/health-center`,
        previewImage: `/directory-previews/planned-parenthood.webp`,
        summary: `Find United States sexual and reproductive health centers by location, service, and appointment type.`,
    },
    {
        id: `toolify`,
        initials: `To`,
        category: `ai`,
        accent: `blue`,
        name: `Toolify`,
        featured: false,
        href: `https://www.toolify.ai/`,
        previewImage: `/directory-previews/toolify.webp`,
        label: `AI tools, apps & models`,
        statuses: [`new`, `international`],
        topics: [`Tools`, `Models`, `Software`, `Generation`],
        summary: `Find AI tools, models, and browser extensions organized by task, category, and usage.`,
    },
    {
        initials: `Or`,
        category: `ai`,
        featured: false,
        accent: `purple`,
        id: `openrouter-models`,
        name: `OpenRouter Models`,
        label: `AI model comparisons`,
        statuses: [`new`, `international`],
        href: `https://openrouter.ai/models`,
        previewImage: `/directory-previews/openrouter-models.webp`,
        topics: [`Models`, `Builders`, `Generation`],
        summary: `Browse AI models and compare pricing, context limits, capabilities, and provider options.`,
    },
    {
        accent: `ink`,
        initials: `Re`,
        category: `ai`,
        id: `replicate`,
        featured: false,
        name: `Replicate`,
        label: `Runnable AI model catalog`,
        statuses: [`new`, `international`],
        href: `https://replicate.com/explore`,
        previewImage: `/directory-previews/replicate.webp`,
        topics: [`Models`, `Builders`, `Generation`],
        summary: `Explore public AI models for images, video, speech, and language with examples and run information.`,
    },
    {
        initials: `Tp`,
        accent: `green`,
        featured: false,
        id: `trustpilot`,
        name: `Trustpilot`,
        category: `business`,
        statuses: [`new`, `international`],
        label: `Businesses & customer reviews`,
        href: `https://www.trustpilot.com/categories`,
        topics: [`Services`, `Products`, `Websites & Apps`],
        summary: `Discover businesses by category and read customer reviews of their products and services.`,
    },
    {
        initials: `Sa`,
        accent: `blue`,
        featured: false,
        category: `business`,
        id: `software-advice`,
        name: `Software Advice`,
        statuses: [`new`, `international`],
        label: `Business software directory`,
        href: `https://www.softwareadvice.com/`,
        topics: [`Products`, `Productivity`, `Small Business`],
        summary: `Compare business software by industry, features, and reviews, with guidance for choosing a product.`,
    },
    {
        accent: `ink`,
        initials: `Wf`,
        id: `wellfound`,
        featured: false,
        name: `Wellfound`,
        category: `business`,
        label: `Startup companies & jobs`,
        href: `https://wellfound.com/jobs`,
        previewImage: `/directory-previews/wellfound.webp`,
        statuses: [`new`, `international`],
        topics: [`Jobs`, `Careers`, `Small Business`],
        summary: `Find startup and technology jobs by role, location, and company, including remote opportunities.`,
    },
    {
        accent: `ink`,
        id: `unsplash`,
        initials: `Un`,
        featured: false,
        name: `Unsplash`,
        category: `creative`,
        href: `https://unsplash.com/`,
        previewImage: `/directory-previews/unsplash.webp`,
        topics: [`Photo`, `Art`, `Design`],
        statuses: [`new`, `international`],
        label: `Photos & visual inspiration`,
        summary: `Search a community contributed library of photos and illustrations by subject, collection, or creator.`,
    },
    {
        initials: `Fs`,
        featured: false,
        accent: `purple`,
        id: `font-squirrel`,
        category: `creative`,
        name: `Font Squirrel`,
        topics: [`Design`, `Development`],
        statuses: [`new`, `international`],
        label: `Fonts & typeface discovery`,
        href: `https://www.fontsquirrel.com/`,
        previewImage: `/directory-previews/font-squirrel.webp`,
        summary: `Browse hand selected fonts by style, language, and license information for design and development projects.`,
    },
    {
        initials: `Ln`,
        featured: false,
        id: `lapa-ninja`,
        accent: `yellow`,
        name: `Lapa Ninja`,
        category: `creative`,
        href: `https://www.lapa.ninja/`,
        previewImage: `/directory-previews/lapa-ninja.webp`,
        topics: [`Design`, `Development`],
        statuses: [`new`, `international`],
        label: `Landing page design gallery`,
        summary: `Discover curated landing pages with full page screenshots, industry categories, and design references.`,
    },
    {
        id: `discogs`,
        accent: `ink`,
        initials: `Di`,
        name: `Discogs`,
        featured: false,
        topics: [`Music`],
        category: `entertainment`,
        href: `https://www.discogs.com/`,
        statuses: [`new`, `international`],
        label: `Records, artists & releases`,
        summary: `Search a community built music database of artists, labels, and releases across genres and formats.`,
    },
    {
        id: `allmusic`,
        initials: `Am`,
        accent: `blue`,
        featured: false,
        name: `AllMusic`,
        topics: [`Music`],
        category: `entertainment`,
        href: `https://www.allmusic.com/`,
        statuses: [`new`, `international`],
        label: `Albums, artists & music guides`,
        summary: `Discover albums, artists, songs, and genres through music profiles, reviews, and detailed search filters.`,
    },
    {
        initials: `Bg`,
        featured: false,
        accent: `orange`,
        topics: [`Gaming`],
        id: `boardgamegeek`,
        name: `BoardGameGeek`,
        category: `entertainment`,
        label: `Board games & card games`,
        href: `https://boardgamegeek.com/`,
        statuses: [`new`, `international`],
        summary: `Explore board and card games with player ratings, reviews, rules resources, and community discussions.`,
    },
    {
        accent: `red`,
        initials: `Nd`,
        featured: false,
        category: `news`,
        id: `us-newspaper-directory`,
        statuses: [`new`, `national`],
        name: `U.S. Newspaper Directory`,
        label: `Newspapers & library holdings`,
        topics: [`History`, `Articles`, `Local Events`],
        href: `https://www.loc.gov/collections/directory-of-us-newspapers-in-american-libraries/`,
        summary: `Find newspapers published in the United States since 1690 and discover which libraries hold copies.`,
    },
    {
        id: `doaj`,
        name: `DOAJ`,
        initials: `Dj`,
        featured: false,
        category: `news`,
        accent: `orange`,
        href: `https://doaj.org/`,
        statuses: [`new`, `international`],
        topics: [`Science`, `Articles`, `Data`],
        label: `Open access journals & articles`,
        summary: `Search open access research journals and articles from publishers around the world by subject and language.`,
    },
    {
        initials: `At`,
        accent: `blue`,
        featured: false,
        category: `auto`,
        id: `autotempest`,
        name: `AutoTempest`,
        topics: [`Cars`, `Used Cars`],
        label: `Used car listing search`,
        href: `https://www.autotempest.com/`,
        statuses: [`new`, `local`, `national`],
        summary: `Search vehicle listings across multiple marketplaces and compare results by make, model, price, and location.`,
    },
    {
        id: `hemmings`,
        initials: `He`,
        featured: false,
        name: `Hemmings`,
        category: `auto`,
        accent: `orange`,
        statuses: [`new`, `international`],
        label: `Classic & collector vehicles`,
        topics: [`Cars`, `Used Cars`, `Motorcycles`],
        href: `https://www.hemmings.com/classifieds/cars-for-sale`,
        summary: `Browse classic and collector vehicle listings, auctions, dealers, and resources for automotive enthusiasts.`,
    },
    {
        accent: `red`,
        initials: `Ct`,
        featured: false,
        category: `auto`,
        id: `cycle-trader`,
        name: `Cycle Trader`,
        topics: [`Motorcycles`],
        href: `https://www.cycletrader.com/`,
        statuses: [`new`, `local`, `national`],
        label: `Motorcycles & powersports listings`,
        summary: `Find new and used motorcycles from dealerships and private sellers across the United States.`,
    },
    {
        initials: `Ct`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `clinical-trials-gov`,
        name: `ClinicalTrials.gov`,
        statuses: [`new`, `international`],
        href: `https://clinicaltrials.gov/`,
        previewImage: `/directory-previews/clinical-trials-gov.webp`,
        label: `Clinical research study registry`,
        topics: [`Disease`, `Biological`, `Policy`],
        summary: `Search clinical research studies by condition, location, recruitment status, and treatment, with study results when available.`,
    },
    {
        initials: `Mc`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `mayo-clinic-conditions`,
        name: `Mayo Clinic Conditions`,
        statuses: [`new`, `international`],
        label: `Disease & condition guides`,
        topics: [`Disease`, `Biological`, `Mental`],
        href: `https://www.mayoclinic.org/diseases-conditions`,
        previewImage: `/directory-previews/mayo-clinic-conditions.webp`,
        summary: `Browse an alphabetical collection of Mayo Clinic guides to diseases, symptoms, diagnosis, and treatment.`,
    },
    {
        initials: `Cc`,
        accent: `green`,
        featured: false,
        category: `health`,
        statuses: [`new`, `international`],
        id: `cleveland-clinic-health-library`,
        name: `Cleveland Clinic Health Library`,
        label: `Health topics & treatment library`,
        href: `https://my.clevelandclinic.org/health`,
        previewImage: `/directory-previews/cleveland-clinic-health-library.webp`,
        topics: [`Disease`, `Wellness`, `Biological`],
        summary: `Find health information organized by diseases, symptoms, treatments, procedures, and body systems.`,
    },
    {
        id: `coursera`,
        initials: `Co`,
        accent: `blue`,
        featured: false,
        name: `Coursera`,
        category: `learning`,
        href: `https://www.coursera.org/`,
        previewImage: `/directory-previews/coursera.webp`,
        statuses: [`new`, `international`],
        label: `Courses, certificates & degrees`,
        topics: [`Skills`, `Students`, `Projects`],
        summary: `Discover online courses, guided projects, certificates, and degree programs from universities and industry partners.`,
    },
    {
        id: `edx`,
        name: `edX`,
        accent: `ink`,
        initials: `Ex`,
        featured: false,
        category: `learning`,
        href: `https://www.edx.org/`,
        previewImage: `/directory-previews/edx.webp`,
        statuses: [`new`, `international`],
        label: `University courses & credentials`,
        topics: [`Skills`, `Students`, `Science`],
        summary: `Explore online courses and professional programs by subject, institution, and learning goal.`,
    },
    {
        initials: `Pg`,
        featured: false,
        accent: `yellow`,
        category: `learning`,
        id: `project-gutenberg`,
        name: `Project Gutenberg`,
        label: `Free ebook library`,
        topics: [`Students`, `Teachers`],
        href: `https://www.gutenberg.org/`,
        previewImage: `/directory-previews/project-gutenberg.webp`,
        statuses: [`new`, `international`],
        summary: `Browse free ebooks by author, title, language, and subject, with download and browser reading options.`,
    },
    {
        id: `airbnb`,
        name: `Airbnb`,
        initials: `Ab`,
        accent: `pink`,
        featured: false,
        category: `travel`,
        href: `https://www.airbnb.com/`,
        previewImage: `/directory-previews/airbnb.webp`,
        statuses: [`new`, `international`],
        label: `Vacation stays & experiences`,
        topics: [`Stays`, `Rentals`, `Vacations`],
        summary: `Discover vacation rentals, rooms, and hosted experiences by destination, travel dates, and preferences.`,
    },
    {
        initials: `Gy`,
        featured: false,
        accent: `orange`,
        id: `getyourguide`,
        category: `travel`,
        name: `GetYourGuide`,
        statuses: [`new`, `international`],
        href: `https://www.getyourguide.com/`,
        label: `Tours, attractions & activities`,
        topics: [`Planners`, `Vacations`, `Family Trips`],
        summary: `Find guided tours, attraction tickets, and local activities with traveler reviews and destination filters.`,
    },
    {
        id: `viator`,
        name: `Viator`,
        initials: `Vi`,
        accent: `green`,
        featured: false,
        category: `travel`,
        href: `https://www.viator.com/`,
        statuses: [`new`, `international`],
        label: `Travel experiences & day trips`,
        topics: [`Planners`, `Vacations`, `Family Trips`],
        summary: `Browse tours, day trips, and activities around the world with reviews and booking information.`,
    },
    {
        initials: `Jl`,
        accent: `blue`,
        featured: false,
        topics: [`Lawyers`],
        id: `justia-lawyers`,
        category: `professionals`,
        name: `Justia Lawyer Directory`,
        href: `https://www.justia.com/lawyers`,
        statuses: [`new`, `local`, `national`],
        label: `Attorneys, legal aid & law firms`,
        summary: `Find United States attorneys, law firms, and legal aid organizations by practice area and location.`,
    },
    {
        initials: `Ad`,
        accent: `blue`,
        featured: false,
        topics: [`Dentists`],
        id: `ada-find-a-dentist`,
        category: `professionals`,
        name: `ADA Find-a-Dentist`,
        href: `https://findadentist.ada.org/`,
        statuses: [`new`, `local`, `national`],
        label: `American Dental Association dentists`,
        summary: `Search ADA member dentists by location, specialty, language, and accepted insurance.`,
    },
    {
        initials: `Dp`,
        accent: `blue`,
        featured: false,
        topics: [`Doctors`],
        id: `doximity-physicians`,
        category: `professionals`,
        name: `Doximity Physicians`,
        statuses: [`new`, `local`, `national`],
        label: `United States physician directory`,
        href: `https://www.doximity.com/directory/physicians`,
        previewImage: `/directory-previews/doximity-physicians.webp`,
        summary: `Browse United States physician profiles by medical specialty and state, including education and practice details.`,
    },
    {
        initials: `Eb`,
        featured: false,
        id: `eventbrite`,
        accent: `orange`,
        name: `Eventbrite`,
        category: `community`,
        topics: [`Events`, `Culture`],
        href: `https://www.eventbrite.com/`,
        previewImage: `/directory-previews/eventbrite.webp`,
        statuses: [`new`, `local`, `international`],
        label: `Local events & community gatherings`,
        summary: `Discover festivals, classes, fundraisers, and community gatherings by location, interest, and date.`,
    },
    {
        initials: `Cn`,
        accent: `blue`,
        featured: false,
        category: `community`,
        id: `charity-navigator`,
        name: `Charity Navigator`,
        statuses: [`new`, `national`],
        topics: [`Leaders`, `Culture`],
        label: `Charity profiles & ratings`,
        href: `https://www.charitynavigator.org/`,
        previewImage: `/directory-previews/charity-navigator.webp`,
        summary: `Find United States charities by cause and review nonprofit profiles, ratings, and financial information.`,
    },
    {
        initials: `Ug`,
        accent: `blue`,
        featured: false,
        category: `community`,
        id: `usa-gov-agency-index`,
        name: `USA.gov Agency Index`,
        statuses: [`new`, `national`],
        topics: [`Government`, `Legal`],
        href: `https://www.usa.gov/agency-index`,
        previewImage: `/directory-previews/usa-gov-agency-index.webp`,
        label: `Federal government agency directory`,
        summary: `Look up United States federal agencies and departments with official websites, contact details, and service information.`,
    },
    {
        initials: `Gr`,
        featured: false,
        accent: `purple`,
        category: `adult`,
        id: `gottman-referral-network`,
        name: `Gottman Referral Network`,
        topics: [`Relationships`, `Therapists`],
        href: `https://gottmanreferralnetwork.com/`,
        previewImage: `/directory-previews/gottman-referral-network.webp`,
        statuses: [`new`, `local`, `international`],
        label: `Gottman-trained relationship therapists`,
        summary: `Find licensed relationship therapists by location, services, and level of Gottman Method training.`,
    },
    {
        initials: `Ie`,
        accent: `green`,
        featured: false,
        category: `adult`,
        id: `iceeft-therapist-directory`,
        name: `ICEEFT Therapist Directory`,
        href: `https://directory.iceeft.com/`,
        previewImage: `/directory-previews/iceeft-therapist-directory.webp`,
        topics: [`Relationships`, `Therapists`],
        statuses: [`new`, `local`, `international`],
        label: `Emotionally focused relationship therapists`,
        summary: `Browse therapists trained in emotionally focused therapy for couples, individuals, and families by location and services.`,
    },
    {
        initials: `Af`,
        category: `ai`,
        accent: `blue`,
        featured: false,
        id: `aitools-fyi`,
        name: `aitools.fyi`,
        href: `https://aitools.fyi/`,
        previewImage: `/directory-previews/aitools-fyi.webp`,
        label: `AI tools by use case`,
        statuses: [`new`, `international`],
        topics: [`Tools`, `Software`, `Generation`],
        summary: `Discover AI tools by category, pricing model, and use case, with tool profiles and newly added listings.`,
    },
    {
        initials: `Ax`,
        category: `ai`,
        accent: `blue`,
        id: `aixploria`,
        featured: false,
        name: `AIxploria`,
        statuses: [`new`, `international`],
        label: `AI tools & category guides`,
        href: `https://www.aixploria.com/en/`,
        previewImage: `/directory-previews/aixploria.webp`,
        topics: [`Tools`, `Software`, `Generation`, `News`],
        summary: `Browse AI tools by category, pricing model, and purpose, with tutorials and regularly updated listings.`,
    },
    {
        initials: `Ft`,
        category: `ai`,
        featured: false,
        accent: `purple`,
        id: `futuretools`,
        name: `Future Tools`,
        statuses: [`new`, `international`],
        href: `https://futuretools.io/tools`,
        previewImage: `/directory-previews/futuretools.webp`,
        label: `Curated AI tools & discoveries`,
        topics: [`Tools`, `Software`, `Generation`, `News`],
        summary: `Explore a curated collection of AI tools by task, category, and pricing, with recommendations and new discoveries.`,
    },
    {
        initials: `Ta`,
        category: `ai`,
        featured: false,
        accent: `purple`,
        id: `topai-tools`,
        name: `TopAI.tools`,
        href: `https://topai.tools/`,
        previewImage: `/directory-previews/topai-tools.webp`,
        statuses: [`new`, `international`],
        label: `AI tools for everyday tasks`,
        topics: [`Tools`, `Software`, `Generation`],
        summary: `Find AI tools by use case and category, with pricing details and alternatives to help compare options.`,
    },
    {
        initials: `At`,
        category: `ai`,
        accent: `blue`,
        featured: false,
        id: `aitoptools`,
        name: `AITopTools`,
        href: `https://aitoptools.com/`,
        previewImage: `/directory-previews/aitoptools.webp`,
        statuses: [`new`, `international`],
        label: `AI software, reviews & categories`,
        topics: [`Tools`, `Software`, `Generation`, `Builders`],
        summary: `Search AI software by task and category, compare pricing, and read user reviews of tools for work and creativity.`,
    },
    {
        initials: `Ot`,
        category: `ai`,
        id: `opentools`,
        featured: false,
        accent: `purple`,
        name: `OpenTools`,
        href: `https://opentools.ai/`,
        previewImage: `/directory-previews/opentools.webp`,
        statuses: [`new`, `international`],
        label: `AI tools, models & integrations`,
        topics: [`Tools`, `Models`, `Software`, `Builders`],
        summary: `Search curated AI tools, models, and MCP servers by task, category, and pricing, with comparisons and practical guides.`,
    },
    {
        initials: `Ss`,
        featured: false,
        accent: `yellow`,
        id: `startup-stash`,
        category: `business`,
        name: `Startup Stash`,
        href: `https://startupstash.com/`,
        previewImage: `/directory-previews/startup-stash.webp`,
        label: `Startup tools & resources`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Marketing`, `Productivity`, `Small Business`],
        summary: `Browse tools and resources for startups by business need, including marketing, collaboration, development, and finance.`,
    },
    {
        id: `betalist`,
        initials: `Bl`,
        accent: `blue`,
        featured: false,
        name: `BetaList`,
        category: `business`,
        href: `https://betalist.com/`,
        previewImage: `/directory-previews/betalist.webp`,
        statuses: [`new`, `international`],
        label: `Early stage startups & products`,
        topics: [`Products`, `Ideas`, `Websites & Apps`, `Small Business`],
        summary: `Discover emerging startups and new products by market, with descriptions and early access links.`,
    },
    {
        id: `appsumo`,
        initials: `As`,
        name: `AppSumo`,
        featured: false,
        accent: `yellow`,
        category: `business`,
        href: `https://appsumo.com/`,
        previewImage: `/directory-previews/appsumo.webp`,
        label: `Business software & deals`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Websites & Apps`, `Small Business`],
        summary: `Discover software for entrepreneurs and small businesses, with product details, customer reviews, and deal information.`,
    },
    {
        id: `openvc`,
        name: `OpenVC`,
        initials: `Ov`,
        accent: `blue`,
        featured: false,
        category: `business`,
        href: `https://www.openvc.app/`,
        previewImage: `/directory-previews/openvc.webp`,
        statuses: [`new`, `international`],
        label: `Startup investor directory`,
        topics: [`Finance`, `Corporate`, `Small Business`],
        summary: `Find venture capital firms and angel investors by geography, investment stage, industry, and check size.`,
    },
    {
        accent: `red`,
        id: `remoteok`,
        initials: `Ro`,
        featured: false,
        name: `Remote OK`,
        category: `business`,
        href: `https://remoteok.com/`,
        previewImage: `/directory-previews/remoteok.webp`,
        statuses: [`new`, `international`],
        label: `Remote jobs & hiring companies`,
        topics: [`Jobs`, `Careers`, `Websites & Apps`],
        summary: `Browse remote job listings by role, technology, salary, and location requirements across companies worldwide.`,
    },
    {
        id: `pexels`,
        name: `Pexels`,
        initials: `Pe`,
        accent: `green`,
        featured: false,
        category: `creative`,
        label: `Stock photos & videos`,
        href: `https://www.pexels.com/`,
        previewImage: `/directory-previews/pexels.webp`,
        statuses: [`new`, `international`],
        topics: [`Photo`, `Video`, `Design`],
        summary: `Discover community contributed photos and videos by subject, collection, or creator for creative projects.`,
    },
    {
        id: `pixabay`,
        initials: `Pi`,
        name: `Pixabay`,
        accent: `green`,
        featured: false,
        category: `creative`,
        href: `https://pixabay.com/`,
        previewImage: `/directory-previews/pixabay.webp`,
        statuses: [`new`, `international`],
        label: `Images, video, music & sound`,
        topics: [`Photo`, `Art`, `Video`, `Music`],
        summary: `Browse photos, illustrations, vectors, videos, music, and sound effects in a searchable creative media library.`,
    },
    {
        id: `coolors`,
        initials: `Co`,
        accent: `blue`,
        name: `Coolors`,
        featured: false,
        category: `creative`,
        label: `Color palette inspiration`,
        statuses: [`new`, `international`],
        topics: [`Design`, `Art`, `Development`],
        href: `https://coolors.co/palettes/trending`,
        previewImage: `/directory-previews/coolors.webp`,
        summary: `Explore color palettes by style, color, popularity, and trend, with options to save, export, or customize a scheme.`,
    },
    {
        initials: `Fu`,
        featured: false,
        accent: `yellow`,
        id: `fonts-in-use`,
        name: `Fonts In Use`,
        category: `creative`,
        href: `https://fontsinuse.com/`,
        previewImage: `/directory-previews/fonts-in-use.webp`,
        statuses: [`new`, `international`],
        label: `Typography examples & typefaces`,
        topics: [`Design`, `Art`, `Development`],
        summary: `Explore real typography examples by typeface, topic, and format in an independent archive of design work.`,
    },
    {
        initials: `Lb`,
        id: `land-book`,
        featured: false,
        name: `Landbook`,
        accent: `purple`,
        category: `creative`,
        href: `https://land-book.com/`,
        previewImage: `/directory-previews/land-book.webp`,
        topics: [`Design`, `Development`],
        statuses: [`new`, `international`],
        label: `Website design inspiration gallery`,
        summary: `Browse curated website designs with filters for industry, style, typography, color, and platform.`,
    },
    {
        accent: `red`,
        initials: `Ol`,
        featured: false,
        id: `one-page-love`,
        category: `creative`,
        name: `One Page Love`,
        href: `https://onepagelove.com/`,
        previewImage: `/directory-previews/one-page-love.webp`,
        topics: [`Design`, `Development`],
        statuses: [`new`, `international`],
        label: `Single page websites & templates`,
        summary: `Explore curated single page websites, section examples, and templates for landing pages, portfolios, and products.`,
    },
    {
        id: `rawg`,
        name: `RAWG`,
        accent: `ink`,
        initials: `Rw`,
        featured: false,
        topics: [`Gaming`],
        href: `https://rawg.io/`,
        previewImage: `/directory-previews/rawg.webp`,
        category: `entertainment`,
        label: `Video games & discovery`,
        statuses: [`new`, `international`],
        summary: `Browse video games by platform, genre, release date, and player ratings, with screenshots and store links.`,
    },
    {
        id: `tvmaze`,
        name: `TVmaze`,
        initials: `Tv`,
        accent: `green`,
        featured: false,
        category: `entertainment`,
        href: `https://www.tvmaze.com/`,
        previewImage: `/directory-previews/tvmaze.webp`,
        statuses: [`new`, `international`],
        topics: [`TV Shows`, `Celebrities`],
        label: `Television shows & episode guides`,
        summary: `Discover television shows with detailed episode guides, cast and character profiles, broadcast schedules, and community lists.`,
    },
    {
        initials: `Ma`,
        accent: `blue`,
        featured: false,
        id: `my-anime-list`,
        name: `MyAnimeList`,
        category: `entertainment`,
        topics: [`TV Shows`, `Movies`],
        href: `https://myanimelist.net/`,
        previewImage: `/directory-previews/my-anime-list.webp`,
        statuses: [`new`, `international`],
        label: `Anime, manga & recommendations`,
        summary: `Discover anime and manga through title profiles, seasonal lists, community ratings, and recommendations.`,
    },
    {
        initials: `Jw`,
        id: `justwatch`,
        featured: false,
        accent: `yellow`,
        name: `JustWatch`,
        category: `entertainment`,
        topics: [`Movies`, `TV Shows`],
        href: `https://www.justwatch.com/`,
        previewImage: `/directory-previews/justwatch.webp`,
        statuses: [`new`, `international`],
        label: `Movies & streaming availability`,
        summary: `Find where movies and television shows are streaming, with filters for provider, genre, release year, and rating.`,
    },
    {
        id: `thetvdb`,
        initials: `Tv`,
        name: `TheTVDB`,
        accent: `green`,
        featured: false,
        category: `entertainment`,
        href: `https://www.thetvdb.com/`,
        previewImage: `/directory-previews/thetvdb.webp`,
        statuses: [`new`, `international`],
        label: `Television, films & episode guides`,
        topics: [`TV Shows`, `Movies`, `Celebrities`],
        summary: `Search television and film profiles with episode guides, cast information, artwork, and fan curated lists.`,
    },
    {
        initials: `Wb`,
        accent: `blue`,
        featured: false,
        category: `news`,
        id: `world-bank-data-catalog`,
        name: `World Bank Data Catalog`,
        statuses: [`new`, `international`],
        label: `Global development datasets`,
        topics: [`Data`, `Charts`, `Government`],
        href: `https://datacatalog.worldbank.org/`,
        previewImage: `/directory-previews/world-bank-data-catalog.webp`,
        summary: `Find development datasets and statistical resources from the World Bank by topic, country, and collection.`,
    },
    {
        initials: `Na`,
        accent: `blue`,
        featured: false,
        category: `news`,
        id: `nasa-open-data`,
        name: `NASA Open Data`,
        topics: [`Science`, `Data`],
        href: `https://data.nasa.gov/`,
        previewImage: `/directory-previews/nasa-open-data.webp`,
        statuses: [`new`, `international`],
        label: `Space & science dataset catalog`,
        summary: `Discover NASA datasets covering space exploration, aeronautics, and science, with links to the archives hosting them.`,
    },
    {
        id: `openalex`,
        initials: `Oa`,
        accent: `blue`,
        featured: false,
        name: `OpenAlex`,
        category: `news`,
        href: `https://openalex.org/`,
        previewImage: `/directory-previews/openalex.webp`,
        statuses: [`new`, `international`],
        topics: [`Science`, `Articles`, `Data`],
        label: `Research works & scholarly connections`,
        summary: `Explore research publications, authors, institutions, and topics in an open catalog of the global research system.`,
    },
    {
        initials: `Oe`,
        accent: `blue`,
        featured: false,
        category: `news`,
        id: `openaire-explore`,
        name: `OpenAIRE Explore`,
        label: `Open research & datasets`,
        statuses: [`new`, `international`],
        href: `https://explore.openaire.eu/`,
        previewImage: `/directory-previews/openaire-explore.webp`,
        topics: [`Science`, `Articles`, `Data`],
        summary: `Search linked publications, research datasets, software, projects, and organizations from open scholarly sources worldwide.`,
    },
    {
        initials: `Dc`,
        accent: `blue`,
        id: `drugs-com`,
        featured: false,
        name: `Drugs.com`,
        category: `health`,
        statuses: [`new`, `international`],
        label: `Medicines & drug information`,
        topics: [`Disease`, `Biological`, `Wellness`],
        href: `https://www.drugs.com/drug_information.html`,
        previewImage: `/directory-previews/drugs-com.webp`,
        summary: `Look up prescription and nonprescription medicines through alphabetical listings, drug classes, and reference guides.`,
    },
    {
        initials: `Nr`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `nord-rare-diseases`,
        topics: [`Disease`, `Biological`],
        name: `NORD Rare Disease Database`,
        statuses: [`new`, `international`],
        label: `Rare diseases & support resources`,
        href: `https://rarediseases.org/rare-diseases/`,
        previewImage: `/directory-previews/nord-rare-diseases.webp`,
        summary: `Explore rare disease reports with information about symptoms, research, treatment options, and patient support organizations.`,
    },
    {
        initials: `Cd`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `cdc-health-topics`,
        name: `CDC Health Topics`,
        statuses: [`new`, `national`],
        label: `Public health topics A-Z`,
        href: `https://www.cdc.gov/health-topics.html`,
        previewImage: `/directory-previews/cdc-health-topics.webp`,
        topics: [`Disease`, `Outbreaks`, `Wellness`, `Policy`],
        summary: `Browse the CDC's alphabetical index of diseases, healthy living, safety, and public health information.`,
    },
    {
        initials: `Mw`,
        accent: `blue`,
        featured: false,
        id: `musclewiki`,
        name: `MuscleWiki`,
        category: `health`,
        href: `https://musclewiki.com/`,
        previewImage: `/directory-previews/musclewiki.webp`,
        topics: [`Fitness`, `Wellness`],
        statuses: [`new`, `international`],
        label: `Exercise library & muscle map`,
        summary: `Find exercise demonstrations by muscle group and equipment through an interactive body map and searchable exercise library.`,
    },
    {
        initials: `Cf`,
        accent: `blue`,
        featured: false,
        category: `auto`,
        id: `carfax-used-cars`,
        name: `CARFAX Used Cars`,
        topics: [`Cars`, `Used Cars`],
        label: `Used cars & vehicle history`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.carfax.com/cars-for-sale`,
        previewImage: `/directory-previews/carfax-used-cars.webp`,
        summary: `Find used vehicles by make, model, budget, and location, with vehicle history information included in the listings.`,
    },
    {
        id: `carvana`,
        initials: `Cv`,
        accent: `blue`,
        name: `Carvana`,
        featured: false,
        category: `auto`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `national`],
        href: `https://www.carvana.com/cars`,
        previewImage: `/directory-previews/carvana.webp`,
        label: `Online used vehicle inventory`,
        summary: `Browse an online used car inventory by price, make, mileage, body type, and features, with delivery information.`,
    },
    {
        accent: `ink`,
        initials: `Cc`,
        featured: false,
        category: `auto`,
        id: `classic-com`,
        name: `CLASSIC.COM`,
        topics: [`Cars`, `Used Cars`],
        href: `https://www.classic.com/`,
        previewImage: `/directory-previews/classic-com.webp`,
        statuses: [`new`, `international`],
        label: `Classic cars & market listings`,
        summary: `Discover classic and specialty cars for sale alongside auction results, model histories, and market data.`,
    },
    {
        initials: `As`,
        featured: false,
        category: `auto`,
        accent: `orange`,
        id: `autoscout24`,
        name: `AutoScout24`,
        statuses: [`new`, `regional`],
        href: `https://www.autoscout24.com/`,
        previewImage: `/directory-previews/autoscout24.webp`,
        label: `European vehicle marketplace`,
        topics: [`Cars`, `Used Cars`, `Motorcycles`],
        summary: `Find new and used vehicles across European markets with filters for make, model, price, mileage, and location.`,
    },
    {
        id: `udacity`,
        initials: `Ud`,
        accent: `blue`,
        name: `Udacity`,
        featured: false,
        category: `learning`,
        statuses: [`new`, `international`],
        href: `https://www.udacity.com/catalog`,
        previewImage: `/directory-previews/udacity.webp`,
        topics: [`Skills`, `Students`, `Projects`],
        label: `Technology courses & career programs`,
        summary: `Browse technology courses and Nanodegree programs by subject, skill level, duration, and career goal, with hands-on projects.`,
    },
    {
        id: `openstax`,
        initials: `Os`,
        featured: false,
        name: `OpenStax`,
        accent: `orange`,
        category: `learning`,
        statuses: [`new`, `international`],
        href: `https://openstax.org/subjects`,
        previewImage: `/directory-previews/openstax.webp`,
        label: `Free textbooks & teaching resources`,
        topics: [`Math`, `Science`, `Students`, `Teachers`],
        summary: `Explore free, peer-reviewed textbooks by subject for high school and college, with online reading and instructor resources.`,
    },
    {
        initials: `Cc`,
        accent: `blue`,
        featured: false,
        id: `codecademy`,
        name: `Codecademy`,
        category: `learning`,
        statuses: [`new`, `international`],
        label: `Coding courses & skill paths`,
        href: `https://www.codecademy.com/catalog`,
        previewImage: `/directory-previews/codecademy.webp`,
        topics: [`Skills`, `Projects`, `Students`, `Testing`],
        summary: `Find coding courses, projects, and career paths by programming language, subject, skill level, and learning format.`,
    },
    {
        id: `alison`,
        name: `Alison`,
        initials: `Al`,
        accent: `green`,
        featured: false,
        category: `learning`,
        href: `https://alison.com/courses`,
        previewImage: `/directory-previews/alison.webp`,
        statuses: [`new`, `international`],
        label: `Free skills & diploma courses`,
        topics: [`Skills`, `Trades`, `Teachers`],
        summary: `Discover free, self-paced courses across technology, business, trades, health, and teaching, with optional paid certificates.`,
    },
    {
        id: `hipcamp`,
        initials: `Hc`,
        name: `Hipcamp`,
        accent: `green`,
        featured: false,
        category: `travel`,
        href: `https://www.hipcamp.com/`,
        previewImage: `/directory-previews/hipcamp.webp`,
        label: `Campsites, cabins & glamping`,
        statuses: [`new`, `local`, `international`],
        topics: [`Stays`, `Vacations`, `Family Trips`],
        summary: `Find tent sites, RV parks, cabins, and glamping stays with destination searches, maps, and traveler reviews.`,
    },
    {
        initials: `Hw`,
        featured: false,
        accent: `orange`,
        id: `hostelworld`,
        category: `travel`,
        name: `Hostelworld`,
        statuses: [`new`, `international`],
        href: `https://www.hostelworld.com/`,
        previewImage: `/directory-previews/hostelworld.webp`,
        label: `Hostels & budget accommodation`,
        topics: [`Stays`, `Vacations`, `Planners`],
        summary: `Discover hostels and budget stays around the world through destination searches, guest reviews, and booking information.`,
    },
    {
        id: `pitchup`,
        initials: `Pu`,
        accent: `green`,
        featured: false,
        category: `travel`,
        name: `Pitchup.com`,
        href: `https://www.pitchup.com/`,
        previewImage: `/directory-previews/pitchup.webp`,
        label: `Campsites & holiday parks`,
        statuses: [`new`, `local`, `international`],
        topics: [`Stays`, `Vacations`, `Family Trips`],
        summary: `Browse campsites, caravan parks, cabins, and glamping by destination, accommodation type, and family-friendly facilities.`,
    },
    {
        id: `campspot`,
        initials: `Cs`,
        featured: false,
        name: `Campspot`,
        accent: `orange`,
        category: `travel`,
        href: `https://www.campspot.com/`,
        previewImage: `/directory-previews/campspot.webp`,
        label: `Campgrounds & RV resorts`,
        statuses: [`new`, `local`, `international`],
        topics: [`Stays`, `Vacations`, `Family Trips`],
        summary: `Find campgrounds, RV resorts, cabins, and glamping across North America with availability, amenities, and booking options.`,
    },
    {
        initials: `Wd`,
        accent: `blue`,
        featured: false,
        category: `professionals`,
        id: `webmd-doctor-directory`,
        name: `WebMD Doctor Directory`,
        href: `https://doctor.webmd.com/`,
        previewImage: `/directory-previews/webmd-doctor-directory.webp`,
        statuses: [`new`, `local`, `national`],
        topics: [`Doctors`, `Dentists`, `Therapists`],
        label: `Doctors, dentists & healthcare providers`,
        summary: `Search physician and dentist profiles by specialty and location, with patient reviews and practice information.`,
    },
    {
        initials: `Sl`,
        accent: `blue`,
        featured: false,
        id: `super-lawyers`,
        topics: [`Lawyers`],
        name: `Super Lawyers`,
        category: `professionals`,
        href: `https://www.superlawyers.com/`,
        previewImage: `/directory-previews/super-lawyers.webp`,
        statuses: [`new`, `local`, `national`],
        label: `Attorney profiles by practice area`,
        summary: `Browse United States attorney profiles by legal issue and location, with practice information and professional background.`,
    },
    {
        initials: `Td`,
        accent: `blue`,
        featured: false,
        id: `topdoctors`,
        topics: [`Doctors`],
        name: `Top Doctors UK`,
        category: `professionals`,
        href: `https://www.topdoctors.co.uk/`,
        previewImage: `/directory-previews/topdoctors.webp`,
        label: `Medical specialists in the UK`,
        statuses: [`new`, `local`, `national`],
        summary: `Find medical specialists by expertise and location, with profiles, patient reviews, and appointment information.`,
    },
    {
        initials: `Ae`,
        id: `allevents`,
        featured: false,
        accent: `orange`,
        name: `AllEvents`,
        category: `community`,
        label: `Events in your city`,
        href: `https://allevents.in/`,
        previewImage: `/directory-previews/allevents.webp`,
        topics: [`Events`, `Culture`],
        statuses: [`new`, `local`, `international`],
        summary: `Discover concerts, festivals, workshops, and community events by city, date, and interest with ticket information.`,
    },
    {
        initials: `Gn`,
        featured: false,
        accent: `orange`,
        id: `greatnonprofits`,
        category: `community`,
        name: `GreatNonprofits`,
        href: `https://greatnonprofits.org/`,
        previewImage: `/directory-previews/greatnonprofits.webp`,
        statuses: [`new`, `local`, `national`],
        topics: [`Leaders`, `Culture`, `Legal`],
        label: `Nonprofit organizations & community reviews`,
        summary: `Discover charities and nonprofit organizations by location and cause through reviews and stories from donors, volunteers, and people served.`,
    },
    {
        initials: `21`,
        accent: `blue`,
        featured: false,
        id: `united-way-211`,
        category: `community`,
        name: `United Way 211`,
        topics: [`Government`, `Legal`],
        statuses: [`new`, `local`, `national`],
        label: `Local community service directories`,
        href: `https://211.org/about-us/your-local-211`,
        previewImage: `/directory-previews/united-way-211.webp`,
        summary: `Find your local United States 211 service and its community resource directory for assistance and public support programs.`,
    },
    {
        initials: `Cd`,
        accent: `green`,
        featured: false,
        category: `adult`,
        id: `counselling-directory`,
        name: `Counselling Directory`,
        statuses: [`new`, `local`, `national`],
        topics: [`Relationships`, `Therapists`],
        label: `Counsellors & relationship therapists`,
        href: `https://www.counselling-directory.org.uk/`,
        previewImage: `/directory-previews/counselling-directory.webp`,
        summary: `Find UK counsellors and therapists by location and therapy type, including relationship and couples support with online and in-person sessions.`,
    },
    {
        initials: `Td`,
        featured: false,
        id: `therapyden`,
        accent: `purple`,
        category: `adult`,
        name: `TherapyDen`,
        statuses: [`new`, `local`, `national`],
        label: `Sexual wellness & intimacy therapists`,
        href: `https://www.therapyden.com/specialties/sex-therapy`,
        previewImage: `/directory-previews/therapyden.webp`,
        topics: [`Therapists`, `Relationships`, `Sexual Wellness`],
        summary: `Browse therapists specializing in sexual health, intimacy, and relationship concerns, with location, insurance, and service filters.`,
    },
];

export const linkedDirectories = directories;
