export type CategoryId =
    | `ai`
    | `auto`
    | `news`
    | `adult`
    | `health`
    | `travel`
    | `creative`
    | `business`
    | `learning`
    | `community`
    | `entertainment`
    | `professionals`;
export type DirectoryAccent = `ink` | `red` | `blue` | `pink` | `green` | `yellow` | `purple` | `orange`;
export type DirectoryStatusId = `new` | `top` | `best` | `local` | `popular` | `trending` | `regional` | `national` | `international`;
export type DirectoryCategoryIcon = `tools` | `design` | `places` | `learning` | `business` | `lifestyle` | `file-text` | `technology` | `communities` | `clapperboard`;

export interface DirectoryStatus {
    label: string;
    description: string;
    id: DirectoryStatusId;
    tone: `green` | `gray` | `red`;
}

export interface DirectoryCategory {
    id: CategoryId;
    label: string;
    topics: string[];
    description: string;
    accent: DirectoryAccent;
    icon: DirectoryCategoryIcon;
}

export interface DirectoryEntry {
    id: string;
    href: string;
    name: string;
    label: string;
    topics: string[];
    summary: string;
    initials: string;
    featured: boolean;
    category: CategoryId;
    accent: DirectoryAccent;
    statuses: DirectoryStatusId[];
}

export const directoryStatuses: DirectoryStatus[] = [
    { id: `new`, tone: `green`, label: `New`, description: `Recently added to this collection` },
    { id: `trending`, tone: `red`, label: `Trending`, description: `Recently popular` },
    { id: `popular`, tone: `green`, label: `Popular`, description: `Consistently popular` },
    { id: `best`, tone: `green`, label: `Best`, description: `Best all round or in all reactions` },
    { id: `top`, tone: `red`, label: `Top`, description: `Most popular all time` },
    { id: `local`, tone: `gray`, label: `Local`, description: `Local to your area` },
    { id: `regional`, tone: `gray`, label: `Regional`, description: `Local to your region` },
    { id: `national`, tone: `gray`, label: `National`, description: `Local to your nation` },
    { id: `international`, tone: `gray`, label: `International`, description: `Global` },
];

export const categories: DirectoryCategory[] = [
    {
        id: `ai`,
        label: `AI`,
        accent: `blue`,
        icon: `technology`,
        description: `Discover AI agents, models, software, and tools for your next idea.`,
        topics: [`Agents`, `Models`, `Software`, `Hardware`, `Tools`, `Generation`, `Builders`, `News`],
    },
    {
        id: `business`,
        accent: `green`,
        label: `Business`,
        icon: `business`,
        description: `Find companies, careers, products, and services for building a business.`,
        topics: [
            `Careers`, `Jobs`, `Experience`, `CEOs`, `Mergers`, `Acquisitions`, `Sales`, `Ideas`, `Marketing`,
            `Finance`, `Services`, `Products`, `Payments`, `Stocks`, `Websites & Apps`, `Productivity`, `Small Business`, `Corporate`,
        ],
    },
    {
        id: `creative`,
        icon: `design`,
        accent: `purple`,
        label: `Creative`,
        description: `Explore creative work, inspiration, and resources for making something new.`,
        topics: [`Art`, `Writing`, `Reading`, `Design`, `Animation`, `Drawing`, `Video`, `Music`, `Photo`, `Development`, `Beauty`, `Production`],
    },
    {
        accent: `pink`,
        id: `entertainment`,
        icon: `clapperboard`,
        label: `Entertainment`,
        description: `Find movies, shows, music, games, and the people behind them.`,
        topics: [
            `Humor`, `Movies`, `TV Shows`, `Horror`, `Celebrities`, `Hollywood`, `Bollywood`,
            `K-Dramas`, `K-Pop`, `Music`, `Gaming`, `Sports`, `Box Office`,
        ],
    },
    {
        id: `news`,
        label: `News`,
        accent: `red`,
        icon: `file-text`,
        description: `Browse news sources, current events, research, and public data.`,
        topics: [`Politics`, `Government`, `Weather`, `Science`, `History`, `Current Events`, `Local Events`, `War`, `Debates`, `Books`, `Articles`, `Data`, `Charts`],
    },
    {
        id: `health`,
        label: `Health`,
        accent: `green`,
        icon: `lifestyle`,
        description: `Explore health information, wellness resources, and ways to stay active.`,
        topics: [`Biological`, `Mental`, `Dental`, `Insurance`, `Wellness`, `Motivation`, `Nutrition`, `Fitness`, `Disease`, `Outbreaks`, `Policy`],
    },
    {
        id: `auto`,
        label: `Auto`,
        icon: `tools`,
        accent: `orange`,
        description: `Browse vehicles, automotive resources, and transport options.`,
        topics: [`Cars`, `Used Cars`, `Maintenance`, `Concepts`, `Driving`, `Motorcycles`, `Airplanes`, `Trains`, `Rentals`],
    },
    {
        id: `learning`,
        accent: `yellow`,
        label: `Learning`,
        icon: `learning`,
        description: `Find courses, books, and educational resources for curious minds.`,
        topics: [`Students`, `Teachers`, `Projects`, `Science`, `Math`, `Skills`, `Trades`, `Coaching`, `Mentoring`, `Testing`],
    },
    {
        id: `travel`,
        accent: `ink`,
        icon: `places`,
        label: `Travel`,
        description: `Discover destinations, places to stay, and ideas for your next trip.`,
        topics: [`Vacations`, `Family Trips`, `Planners`, `Flights`, `Stays`, `Rentals`],
    },
    {
        accent: `blue`,
        icon: `business`,
        id: `professionals`,
        label: `Professionals`,
        description: `Find healthcare and legal professionals by specialty and location.`,
        topics: [`Doctors`, `Lawyers`, `Therapists`, `Dentists`],
    },
    {
        accent: `green`,
        id: `community`,
        label: `Community`,
        icon: `communities`,
        description: `Connect with local groups, events, organizations, and community resources.`,
        topics: [`Events`, `Leaders`, `Churches`, `Religious Sites`, `Culture`, `Government`, `Legal`, `Policing`, `Crime`],
    },
    {
        id: `adult`,
        label: `Adult`,
        accent: `purple`,
        icon: `lifestyle`,
        description: `Explore dating, relationships, sexual wellness, and educational resources for adults.`,
        topics: [`Dating`, `Relationships`, `Sexual Wellness`, `Education`, `Therapists`, `Communities`],
    },
];

export const directories: DirectoryEntry[] = [
    {
        id: `futurepedia`,
        initials: `Fu`,
        category: `ai`,
        accent: `purple`,
        featured: true,
        name: `Futurepedia`,
        label: `AI tools by category`,
        topics: [`Tools`, `Generation`],
        statuses: [`international`],
        href: `https://www.futurepedia.io/`,
        summary: `Explore categorized AI tools for creative work, productivity, and research.`,
    },
    {
        initials: `Hs`,
        category: `ai`,
        accent: `orange`,
        featured: false,
        id: `hugging-face-spaces`,
        label: `AI app directory`,
        statuses: [`international`],
        name: `Hugging Face Spaces`,
        topics: [`Models`, `Generation`, `Builders`],
        href: `https://huggingface.co/spaces`,
        summary: `Browse interactive AI apps and demos shared by the developer community.`,
    },
    {
        initials: `At`,
        category: `ai`,
        accent: `green`,
        featured: false,
        id: `alternative-to`,
        name: `AlternativeTo`,
        topics: [`Tools`, `Software`],
        label: `Software alternatives`,
        statuses: [`international`],
        href: `https://alternativeto.net/`,
        summary: `Compare community recommended alternatives to the apps and services you use.`,
    },
    {
        initials: `Oa`,
        category: `ai`,
        accent: `green`,
        featured: false,
        id: `open-alternative`,
        name: `OpenAlternative`,
        topics: [`Tools`, `Software`],
        statuses: [`international`],
        label: `Open source alternatives`,
        href: `https://openalternative.co/`,
        summary: `Find open source replacements for popular software and services.`,
    },
    {
        initials: `Ad`,
        category: `ai`,
        accent: `blue`,
        featured: false,
        id: `ai-tools-directory`,
        name: `AI Tools Directory`,
        label: `Curated AI software`,
        topics: [`Tools`, `Software`, `Generation`],
        statuses: [`new`, `international`],
        href: `https://aitoolsdirectory.com/`,
        summary: `Browse AI tools by category and use case for writing, design, coding, and everyday work.`,
    },
    {
        initials: `Aa`,
        category: `ai`,
        accent: `red`,
        featured: false,
        id: `ai-agents-directory`,
        name: `AI Agents Directory`,
        topics: [`Agents`, `Builders`],
        label: `Agents & frameworks`,
        statuses: [`new`, `international`],
        href: `https://aiagentsdirectory.com/`,
        summary: `Discover AI agents and frameworks organized by workflow, category, and use case.`,
    },
    {
        initials: `Hm`,
        category: `ai`,
        accent: `yellow`,
        featured: false,
        id: `hugging-face-models`,
        topics: [`Models`, `Builders`],
        name: `Hugging Face Models`,
        label: `Machine learning models`,
        statuses: [`new`, `international`],
        href: `https://huggingface.co/models`,
        summary: `Find machine learning models by task, library, language, and license.`,
    },
    {
        id: `product-hunt`,
        initials: `Ph`,
        accent: `orange`,
        featured: true,
        category: `business`,
        name: `Product Hunt`,
        statuses: [`international`],
        label: `New products & launches`,
        topics: [`Ideas`, `Products`, `Websites & Apps`],
        href: `https://www.producthunt.com/`,
        summary: `Find new products, tools, and ideas shared by makers and their communities.`,
    },
    {
        id: `g2`,
        initials: `G2`,
        name: `G2`,
        accent: `purple`,
        featured: false,
        category: `business`,
        statuses: [`international`],
        label: `Business software reviews`,
        topics: [`Products`, `Services`, `Websites & Apps`],
        href: `https://www.g2.com/`,
        summary: `Find and compare business software using product listings and reviews.`,
    },
    {
        id: `crunchbase`,
        initials: `Cr`,
        accent: `blue`,
        featured: false,
        name: `Crunchbase`,
        category: `business`,
        label: `Company discovery`,
        statuses: [`international`],
        topics: [`CEOs`, `Finance`, `Corporate`],
        href: `https://www.crunchbase.com/`,
        summary: `Explore company profiles, funding information, and market activity.`,
    },
    {
        id: `capterra`,
        initials: `Ca`,
        accent: `orange`,
        featured: false,
        name: `Capterra`,
        category: `business`,
        label: `Software comparisons`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Small Business`],
        href: `https://www.capterra.com/`,
        summary: `Browse business software categories and compare features, pricing, and verified user reviews.`,
    },
    {
        id: `getapp`,
        initials: `Ga`,
        name: `GetApp`,
        accent: `green`,
        featured: false,
        category: `business`,
        label: `Apps for businesses`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Websites & Apps`],
        href: `https://www.getapp.com/`,
        summary: `Explore business applications by category with product comparisons and customer reviews.`,
    },
    {
        id: `clutch`,
        initials: `Cl`,
        name: `Clutch`,
        accent: `red`,
        featured: false,
        category: `business`,
        label: `Business service providers`,
        statuses: [`new`, `international`],
        topics: [`Services`, `Marketing`, `Small Business`],
        href: `https://clutch.co/`,
        summary: `Find agencies and business service providers through detailed profiles and client reviews.`,
    },
    {
        id: `saashub`,
        initials: `Sh`,
        name: `SaaSHub`,
        accent: `blue`,
        featured: false,
        category: `business`,
        label: `Software & startup discovery`,
        statuses: [`new`, `international`],
        topics: [`Products`, `Productivity`, `Websites & Apps`],
        href: `https://www.saashub.com/`,
        summary: `Discover software alternatives, startup products, and tools organized by business needs.`,
    },
    {
        id: `awwwards`,
        initials: `Aw`,
        accent: `red`,
        featured: true,
        name: `Awwwards`,
        category: `creative`,
        label: `Website inspiration`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://www.awwwards.com/`,
        summary: `Browse recognized websites and creative work from designers around the world.`,
    },
    {
        id: `behance`,
        initials: `Be`,
        accent: `blue`,
        featured: false,
        name: `Behance`,
        category: `creative`,
        topics: [`Art`, `Design`, `Photo`],
        label: `Creative portfolios`,
        statuses: [`international`],
        href: `https://www.behance.net/`,
        summary: `Explore portfolios and projects shared by a global creative community.`,
    },
    {
        id: `mobbin`,
        initials: `Mo`,
        name: `Mobbin`,
        accent: `blue`,
        featured: true,
        category: `creative`,
        label: `App design patterns`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://mobbin.com/`,
        summary: `Search real app screens, interface elements, and product flows for design reference.`,
    },
    {
        id: `siteinspire`,
        initials: `Si`,
        accent: `pink`,
        featured: false,
        name: `Siteinspire`,
        category: `creative`,
        label: `Curated websites`,
        topics: [`Design`, `Development`],
        statuses: [`international`],
        href: `https://www.siteinspire.com/`,
        summary: `Browse a curated gallery of websites and the designers behind them.`,
    },
    {
        id: `good-on-you`,
        initials: `Gy`,
        accent: `green`,
        featured: false,
        name: `Good On You`,
        category: `creative`,
        topics: [`Beauty`, `Design`],
        label: `Fashion brand ratings`,
        statuses: [`international`],
        href: `https://directory.goodonyou.eco/`,
        summary: `Look up fashion and beauty brands through sustainability ratings and guides.`,
    },
    {
        id: `google-fonts`,
        initials: `Gf`,
        accent: `blue`,
        featured: false,
        name: `Google Fonts`,
        category: `creative`,
        topics: [`Design`, `Development`],
        label: `Fonts & typography`,
        statuses: [`new`, `international`],
        href: `https://fonts.google.com/`,
        summary: `Browse font families and typography resources for websites and creative projects.`,
    },
    {
        id: `dribbble`,
        initials: `Dr`,
        accent: `pink`,
        featured: false,
        name: `Dribbble`,
        category: `creative`,
        topics: [`Art`, `Design`, `Animation`],
        label: `Designers & design inspiration`,
        statuses: [`new`, `international`],
        href: `https://dribbble.com/`,
        summary: `Explore visual design work and discover creative professionals by specialty.`,
    },
    {
        id: `artstation`,
        initials: `As`,
        accent: `ink`,
        featured: false,
        name: `ArtStation`,
        category: `creative`,
        label: `Artists & digital portfolios`,
        statuses: [`new`, `international`],
        topics: [`Art`, `Drawing`, `Animation`],
        href: `https://www.artstation.com/`,
        summary: `Discover digital art, illustrations, and portfolios from artists working in games, film, and beyond.`,
    },
    {
        id: `imdb`,
        initials: `Im`,
        name: `IMDb`,
        accent: `yellow`,
        featured: true,
        category: `entertainment`,
        label: `Movies, shows & people`,
        statuses: [`new`, `international`],
        topics: [`Movies`, `TV Shows`, `Celebrities`],
        href: `https://www.imdb.com/`,
        summary: `Search movie and television titles, cast and crew profiles, reviews, and viewing information.`,
    },
    {
        id: `tmdb`,
        initials: `Tm`,
        accent: `green`,
        featured: false,
        name: `The Movie Database`,
        category: `entertainment`,
        topics: [`Movies`, `TV Shows`],
        label: `Community movie & TV catalog`,
        statuses: [`new`, `international`],
        href: `https://www.themoviedb.org/`,
        summary: `Explore a community maintained database of movies, television shows, actors, and artwork.`,
    },
    {
        id: `letterboxd`,
        initials: `Lb`,
        accent: `orange`,
        featured: false,
        name: `Letterboxd`,
        category: `entertainment`,
        topics: [`Movies`, `Horror`],
        label: `Film discovery & lists`,
        statuses: [`new`, `international`],
        href: `https://letterboxd.com/`,
        summary: `Discover films through member reviews, watchlists, and collections from a film community.`,
    },
    {
        id: `igdb`,
        initials: `Ig`,
        name: `IGDB`,
        accent: `purple`,
        featured: false,
        topics: [`Gaming`],
        category: `entertainment`,
        label: `Video game database`,
        statuses: [`new`, `international`],
        href: `https://www.igdb.com/`,
        summary: `Browse video games, genres, platforms, release information, and community ratings.`,
    },
    {
        id: `musicbrainz`,
        initials: `Mb`,
        accent: `orange`,
        featured: false,
        name: `MusicBrainz`,
        topics: [`Music`],
        category: `entertainment`,
        label: `Open music encyclopedia`,
        statuses: [`new`, `international`],
        href: `https://musicbrainz.org/`,
        summary: `Explore an open catalog of artists, recordings, releases, and related music information.`,
    },
    {
        id: `allsides`,
        initials: `As`,
        category: `news`,
        accent: `purple`,
        featured: false,
        name: `AllSides`,
        label: `News source perspectives`,
        statuses: [`new`, `national`],
        topics: [`Politics`, `Debates`, `Articles`],
        href: `https://www.allsides.com/media-bias`,
        summary: `Browse news sources and media bias ratings to compare perspectives on current events.`,
    },
    {
        id: `ground-news`,
        initials: `Gn`,
        category: `news`,
        accent: `ink`,
        featured: false,
        name: `Ground News`,
        label: `News source comparison`,
        statuses: [`new`, `international`],
        topics: [`Politics`, `Current Events`, `Local Events`],
        href: `https://ground.news/`,
        summary: `Compare coverage across news sources and browse stories by topic or location.`,
    },
    {
        id: `data-gov`,
        initials: `Dg`,
        category: `news`,
        accent: `blue`,
        featured: false,
        name: `Data.gov`,
        label: `Public data catalog`,
        statuses: [`new`, `national`],
        topics: [`Data`, `Science`],
        href: `https://catalog.data.gov/`,
        summary: `Search public datasets from United States government agencies and participating organizations.`,
    },
    {
        initials: `Ow`,
        category: `news`,
        accent: `red`,
        featured: false,
        id: `our-world-in-data`,
        name: `Our World in Data`,
        label: `Research, data & charts`,
        statuses: [`new`, `international`],
        topics: [`Data`, `Charts`, `Science`],
        href: `https://ourworldindata.org/`,
        summary: `Explore research topics, datasets, and charts covering global conditions and long term change.`,
    },
    {
        id: `all-trails`,
        initials: `At`,
        accent: `green`,
        featured: false,
        category: `health`,
        name: `AllTrails`,
        topics: [`Fitness`, `Wellness`],
        label: `Trails & outdoor places`,
        statuses: [`local`, `international`],
        href: `https://www.alltrails.com/`,
        summary: `Explore trails, parks, and routes for your next time outdoors.`,
    },
    {
        id: `medlineplus`,
        initials: `Mp`,
        accent: `blue`,
        featured: false,
        category: `health`,
        name: `MedlinePlus`,
        label: `Health topic library`,
        statuses: [`new`, `national`],
        topics: [`Disease`, `Wellness`, `Biological`],
        href: `https://medlineplus.gov/healthtopics.html`,
        summary: `Browse health topics with information from the United States National Library of Medicine.`,
    },
    {
        initials: `Nh`,
        accent: `blue`,
        featured: false,
        category: `health`,
        id: `nhs-conditions`,
        name: `NHS Conditions`,
        label: `Conditions A to Z`,
        statuses: [`new`, `national`],
        topics: [`Disease`, `Mental`, `Dental`],
        href: `https://www.nhs.uk/conditions/`,
        summary: `Find National Health Service information about health conditions, symptoms, and care in the UK.`,
    },
    {
        id: `nutrition-gov`,
        initials: `Ng`,
        accent: `green`,
        featured: false,
        category: `health`,
        name: `Nutrition.gov`,
        topics: [`Nutrition`, `Wellness`],
        label: `Food & nutrition resources`,
        statuses: [`new`, `national`],
        href: `https://www.nutrition.gov/topics`,
        summary: `Browse United States government nutrition resources by topic and stage of life.`,
    },
    {
        initials: `Mh`,
        accent: `green`,
        featured: false,
        category: `health`,
        id: `mental-health-america`,
        name: `Mental Health America`,
        topics: [`Mental`, `Wellness`, `Policy`],
        label: `Mental health resource library`,
        statuses: [`new`, `national`],
        href: `https://mhanational.org/resources/`,
        summary: `Explore mental health guides, fact sheets, and support resources from a national nonprofit.`,
    },
    {
        id: `autotrader`,
        initials: `Au`,
        category: `auto`,
        accent: `blue`,
        featured: false,
        name: `Autotrader`,
        label: `New & used car listings`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.autotrader.com/`,
        summary: `Search new and used vehicles from dealerships and private sellers in the United States.`,
    },
    {
        id: `cars-com`,
        initials: `Ca`,
        category: `auto`,
        accent: `purple`,
        featured: false,
        name: `Cars.com`,
        label: `Cars, dealers & research`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.cars.com/`,
        summary: `Compare vehicle listings, dealership profiles, reviews, and car research in the United States.`,
    },
    {
        id: `cargurus`,
        initials: `Cg`,
        category: `auto`,
        accent: `blue`,
        featured: false,
        name: `CarGurus`,
        label: `Vehicle & dealer discovery`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.cargurus.com/`,
        summary: `Find vehicle listings and compare asking prices, deal information, and sellers.`,
    },
    {
        initials: `Bt`,
        category: `auto`,
        accent: `yellow`,
        featured: false,
        id: `bring-a-trailer`,
        name: `Bring a Trailer`,
        label: `Classic & enthusiast auctions`,
        topics: [`Cars`, `Used Cars`, `Motorcycles`],
        statuses: [`new`, `international`],
        href: `https://bringatrailer.com/`,
        summary: `Browse curated vehicle auctions, past listings, and discussion from an enthusiast community.`,
    },
    {
        id: `cars-and-bids`,
        initials: `Cb`,
        category: `auto`,
        accent: `green`,
        featured: false,
        name: `Cars & Bids`,
        label: `Modern enthusiast car auctions`,
        topics: [`Cars`, `Used Cars`],
        statuses: [`new`, `national`],
        href: `https://carsandbids.com/`,
        summary: `Discover auctions for modern enthusiast cars, trucks, and SUVs with detailed listing information.`,
    },
    {
        id: `class-central`,
        initials: `Cc`,
        accent: `yellow`,
        featured: true,
        category: `learning`,
        name: `Class Central`,
        label: `Online courses`,
        topics: [`Skills`, `Students`, `Science`],
        statuses: [`international`],
        href: `https://www.classcentral.com/`,
        summary: `Search online courses across universities and learning providers.`,
    },
    {
        id: `open-library`,
        initials: `Ol`,
        accent: `yellow`,
        featured: false,
        category: `learning`,
        name: `Open Library`,
        topics: [`Students`, `Teachers`],
        label: `Books & reading`,
        statuses: [`international`],
        href: `https://openlibrary.org/`,
        summary: `Search an open catalog of books, authors, and reading resources.`,
    },
    {
        id: `merlot`,
        initials: `Me`,
        name: `MERLOT`,
        accent: `green`,
        featured: false,
        category: `learning`,
        label: `Learning materials & resources`,
        statuses: [`new`, `international`],
        topics: [`Students`, `Teachers`, `Skills`],
        href: `https://www.merlot.org/merlot/`,
        summary: `Find curated learning materials and resources contributed by educators and institutions.`,
    },
    {
        initials: `Oc`,
        accent: `red`,
        featured: false,
        id: `mit-opencourseware`,
        category: `learning`,
        name: `MIT OpenCourseWare`,
        label: `Open university course materials`,
        statuses: [`new`, `international`],
        topics: [`Math`, `Science`, `Students`],
        href: `https://ocw.mit.edu/`,
        summary: `Browse free course materials from Massachusetts Institute of Technology classes by subject.`,
    },
    {
        id: `oer-commons`,
        initials: `Oc`,
        accent: `blue`,
        featured: false,
        category: `learning`,
        name: `OER Commons`,
        label: `Open educational resources`,
        statuses: [`new`, `international`],
        topics: [`Projects`, `Teachers`, `Students`],
        href: `https://oercommons.org/`,
        summary: `Discover open teaching and learning materials by subject, education level, and resource type.`,
    },
    {
        id: `yelp`,
        initials: `Ye`,
        name: `Yelp`,
        accent: `pink`,
        featured: false,
        category: `travel`,
        topics: [`Planners`, `Family Trips`],
        label: `Local places & services`,
        statuses: [`local`, `regional`],
        href: `https://www.yelp.com/`,
        summary: `Discover local restaurants, shops, and services through community reviews.`,
    },
    {
        id: `atlas-obscura`,
        initials: `Ao`,
        accent: `ink`,
        featured: false,
        category: `travel`,
        name: `Atlas Obscura`,
        label: `Unusual places`,
        statuses: [`international`],
        topics: [`Vacations`, `Planners`, `Family Trips`],
        href: `https://www.atlasobscura.com/`,
        summary: `Discover remarkable destinations and lesser known places around the world.`,
    },
    {
        id: `booking-com`,
        initials: `Bc`,
        accent: `blue`,
        featured: false,
        category: `travel`,
        name: `Booking.com`,
        label: `Stays & travel bookings`,
        statuses: [`new`, `international`],
        topics: [`Stays`, `Flights`, `Rentals`],
        href: `https://www.booking.com/`,
        summary: `Discover accommodation, flights, and rental options for destinations around the world.`,
    },
    {
        id: `tripadvisor`,
        initials: `Ta`,
        accent: `green`,
        featured: false,
        category: `travel`,
        name: `Tripadvisor`,
        label: `Places, stays & traveler reviews`,
        statuses: [`new`, `local`, `international`],
        topics: [`Stays`, `Planners`, `Vacations`],
        href: `https://www.tripadvisor.com/`,
        summary: `Explore hotels, restaurants, attractions, and experiences with reviews from travelers.`,
    },
    {
        id: `wikivoyage`,
        initials: `Wv`,
        accent: `blue`,
        featured: false,
        category: `travel`,
        name: `Wikivoyage`,
        label: `Open destination guides`,
        statuses: [`new`, `international`],
        topics: [`Planners`, `Vacations`, `Family Trips`],
        href: `https://en.wikivoyage.org/wiki/Main_Page`,
        summary: `Browse collaboratively written destination guides and practical travel information.`,
    },
    {
        id: `healthgrades`,
        initials: `Hg`,
        accent: `blue`,
        featured: false,
        name: `Healthgrades`,
        category: `professionals`,
        topics: [`Doctors`, `Dentists`],
        label: `Doctors & healthcare facilities`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.healthgrades.com/`,
        summary: `Find United States doctors, dentists, hospitals, and healthcare professionals by specialty and location.`,
    },
    {
        id: `zocdoc`,
        initials: `Zo`,
        name: `Zocdoc`,
        accent: `yellow`,
        featured: false,
        category: `professionals`,
        label: `Healthcare providers & appointments`,
        topics: [`Doctors`, `Dentists`, `Therapists`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.zocdoc.com/`,
        summary: `Discover United States healthcare providers and appointment options by specialty, location, and insurance.`,
    },
    {
        initials: `Pt`,
        accent: `green`,
        featured: false,
        id: `psychology-today`,
        name: `Psychology Today`,
        topics: [`Therapists`],
        category: `professionals`,
        label: `Therapist directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.psychologytoday.com/us/therapists`,
        summary: `Search United States therapist profiles by location, specialty, and treatment approach.`,
    },
    {
        id: `avvo`,
        initials: `Av`,
        name: `Avvo`,
        accent: `blue`,
        featured: false,
        topics: [`Lawyers`],
        category: `professionals`,
        label: `Lawyers & legal help`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.avvo.com/`,
        summary: `Find United States attorneys by practice area and location with profiles and client reviews.`,
    },
    {
        id: `findlaw`,
        initials: `Fl`,
        name: `FindLaw`,
        accent: `orange`,
        featured: false,
        topics: [`Lawyers`],
        category: `professionals`,
        label: `Attorney directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://lawyers.findlaw.com/`,
        summary: `Browse United States lawyers and law firms by legal issue and location.`,
    },
    {
        id: `meetup`,
        initials: `Me`,
        name: `Meetup`,
        accent: `red`,
        featured: true,
        category: `community`,
        label: `Groups & events`,
        topics: [`Events`, `Culture`],
        statuses: [`local`, `regional`, `international`],
        href: `https://www.meetup.com/`,
        summary: `Find local groups and events built around shared interests.`,
    },
    {
        id: `idealist`,
        initials: `Id`,
        name: `Idealist`,
        accent: `blue`,
        featured: false,
        category: `community`,
        label: `Nonprofits & volunteering`,
        statuses: [`new`, `local`, `international`],
        topics: [`Events`, `Leaders`, `Culture`],
        href: `https://www.idealist.org/en`,
        summary: `Discover nonprofit organizations, volunteer opportunities, events, and ways to support communities.`,
    },
    {
        id: `findhelp`,
        initials: `Fh`,
        name: `findhelp`,
        accent: `green`,
        featured: false,
        category: `community`,
        label: `Community support programs`,
        topics: [`Legal`, `Government`],
        statuses: [`new`, `local`, `regional`, `national`],
        href: `https://www.findhelp.org/`,
        summary: `Search United States community programs offering free or reduced cost support by ZIP code.`,
    },
    {
        id: `guidestar`,
        initials: `Gs`,
        name: `GuideStar`,
        accent: `blue`,
        featured: false,
        category: `community`,
        topics: [`Leaders`, `Culture`],
        label: `Nonprofit organization profiles`,
        statuses: [`new`, `national`],
        href: `https://www.guidestar.org/`,
        summary: `Search United States nonprofit organizations and explore profiles, missions, and public financial information.`,
    },
    {
        id: `church-finder`,
        initials: `Cf`,
        accent: `purple`,
        featured: false,
        name: `Church Finder`,
        category: `community`,
        label: `Local church directory`,
        topics: [`Churches`, `Religious Sites`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.churchfinder.com/`,
        summary: `Find Christian churches in the United States by city, denomination, and congregation profile.`,
    },
    {
        initials: `Ms`,
        accent: `pink`,
        featured: false,
        category: `adult`,
        id: `meetup-singles`,
        name: `Meetup Singles`,
        label: `Singles groups & events`,
        statuses: [`new`, `local`, `international`],
        topics: [`Dating`, `Relationships`, `Communities`],
        href: `https://www.meetup.com/topics/singles/`,
        summary: `Browse singles groups and social events for meeting people with shared interests.`,
    },
    {
        id: `aasect`,
        initials: `Aa`,
        accent: `purple`,
        featured: false,
        category: `adult`,
        name: `AASECT Directory`,
        label: `Sexual wellness professionals`,
        statuses: [`new`, `international`],
        topics: [`Sexual Wellness`, `Education`, `Therapists`],
        href: `https://www.aasect.org/referral-directory`,
        summary: `Find certified sexuality educators, counselors, and therapists by country or United States state.`,
    },
    {
        initials: `At`,
        accent: `blue`,
        featured: false,
        category: `adult`,
        id: `aamft-therapist-locator`,
        name: `AAMFT Therapist Locator`,
        label: `Marriage & relationship therapists`,
        topics: [`Relationships`, `Therapists`],
        statuses: [`new`, `local`, `national`],
        href: `https://www.therapistlocator.net/`,
        summary: `Browse marriage and family therapists offering support for individuals, couples, and relationships.`,
    },
    {
        initials: `Pp`,
        accent: `pink`,
        featured: false,
        category: `adult`,
        id: `planned-parenthood`,
        topics: [`Sexual Wellness`],
        name: `Planned Parenthood`,
        label: `Sexual health center directory`,
        statuses: [`new`, `local`, `national`],
        href: `https://www.plannedparenthood.org/health-center`,
        summary: `Find United States sexual and reproductive health centers by location, service, and appointment type.`,
    },
];

export const linkedDirectories = directories;
